### ISSUE TITLE
connection.execute fails silently when called many times

### ISSUE THREAD

**Issue by grug** [oracle/node-oracledb#335] opened 2016-01-21 05:16 UTC
Hi all,

Hopefully I can explain this one well enough :P 

I believe I have found an improvement to the library that will save some future users the pain I had to go through.

I'll start by saying the following description is a problem I *used* to have and now I don't anymore, because I finally identified what needed fixing in my code. However, it took me a lot longer to fix because my application due to the underlying problem.

In my node application, I have a function that takes an array (of objects) of an arbitrary length (i.e. it is not known until runtime how long this array will be). For each entry in the array, I want to insert a row into a table. However, I also have a function that is to be called after this function has executed and I want to make sure this one finishes executing first. Because I also care about closing all connections to the database as I don't want to leave them hanging.

My array of objects looked something like this (I've omitted somethings, but you'll be able to fill in the blanks):
```
var myThings = [
    {
        foo: 'bar'
    },
    {
        foo: 'baz'
    }
    {
        foo: 'bill'
    }
];
```

Pretty basic.

Now, the calling code that I have looks something like this:
```
var oracledb = require('oracledb');
var fs = require('fs');

mustBeCalledFirst(myThings, function() {
    mustBeCalledSecond();
});

function mustBeCalledFirst(myThings, callback) {
    var myQuery = fs.readFileSync('some/path/to/a/file/where/i/have/a/query/saved.sql', 'utf8');
    oracledb.getConnection('MY CONNECTION DATA HERE', function(err, connection) {
        var numThings = myThings.length;
        myThings.forEach(function(thing) {
            connection.execute(
                myQuery,
                {someBinding: thing.foo},
                function(err, result) {
                    connection.commit(function(err) {console.log('error!', err.message);});
                    numThings--;
                    if (numThings == 0) { // No more things left to insert into our db.
                         connection.release(function(err) {console.log('error!', err.message);});
                         callback(); // We are done. We have committed all our things.
                         return;
                    }
                }
            );
        });
    });
};

function mustBeCalledSecond() {
    console.log('doesn't matter what happens here');
};
```

In reality, `myThings` will be sent through to my API without my knowing how many entries it has. The problem with the above code is two-fold:
1. The connection object is getting hit multiple times and is not necessarily finishing executing one query before being asked to execute another one. This causes my node application to crash.
2. It causes the app to crash *silently*. No error, no stack trace, no exit code. The application simply terminates.

The fact that it is terminating silently was the killer in working this one out. I eventually figured out that I shouldn't be reusing the same connection when performing queries of this nature, and I refactored my code to only create a connection when needed, and as soon as the individual query is done executing, I release my connection. I could also have used a connection pool and adopted the same sort of approach.

Can anyone shed any light into *why* this crashes node apps silently, with no error?

Thanks,
Dave

**Comment by dmcghan** [comment] 2016-01-21 15:19
Hi Dave,

It appears your code is ignoring errors that you may have been passed. You must check for error after each async call in Node.js. I see you're checking for errors with connection.commit and connection.release, but not with oracledb.getConnection or connection.execute. Here's a rewrite that demonstrates what I mean. Note that I'm passing the error to the callback so that it can know if it should proceed or not.

```javascript
var oracledb = require('oracledb');
var fs = require('fs');

mustBeCalledFirst(myThings, function() {
    mustBeCalledSecond();
});

function mustBeCalledFirst(myThings, callback) {
    var myQuery = fs.readFileSync('some/path/to/a/file/where/i/have/a/query/saved.sql', 'utf8');
    oracledb.getConnection('MY CONNECTION DATA HERE', function(err, connection) {
        var numThings;

        if (err) {
            console.error(err);
            callback(err);
            return;
        }

        numThings = myThings.length;

        myThings.forEach(function(thing) {
            connection.execute(
                myQuery,
                {someBinding: thing.foo},
                function(err, result) {
                    if (err) {
                        console.error(err);
                        callback(err);
                        return;
                    }

                    connection.commit(function(err) {
                        if (err) {
                            console.error(err);
                            callback(err);
                            return;
                        }
                    });

                    numThings--;

                    if (numThings == 0) { // No more things left to insert into our db.
                        connection.release(function(err) {
                            if (err) {
                                console.error(err);
                                return;
                            }
                        });

                        callback(err); // We are done. We have committed all our things.
                        return;
                    }
                }
            );
        });
    });
}

function mustBeCalledSecond() {
    console.log('doesn\'t matter what happens here');
}
```

Also, the fact that you're committing after each iteration is a little surprising. What happens when you've committed a lot of work and then a problem occurs? You would have to write a bunch more code that can figure out where a problem occurred and and then finish the job from that point.

As noted [in the documentation](https://github.com/oracle/node-oracledb/blob/master/doc/api.md#release), the driver will automatically rollback uncommitted work when you release a connection. Why not just leverage the transaction and only commit at the end?

Here's another rewrite that domonstrates what that might look like:
```javascript
var oracledb = require('oracledb');
var fs = require('fs');

mustBeCalledFirst(myThings, function() {
    mustBeCalledSecond();
});

function mustBeCalledFirst(myThings, callback) {
    var myQuery = fs.readFileSync('some/path/to/a/file/where/i/have/a/query/saved.sql', 'utf8');

    oracledb.getConnection('MY CONNECTION DATA HERE', function(err, connection) {
        var numThings;

        if (err) {
            console.error(err);
            callback(err);
            return;
        }

        numThings = myThings.length;

        myThings.forEach(function(thing) {
            connection.execute(
                myQuery,
                {someBinding: thing.foo},
                function(err, result) {
                    if (err) {
                        console.error(err);
                        callback(err);
                        return;
                    }

                    numThings--;

                    if (numThings == 0) { // No more things left to insert into our db.
                        connection.commit(function(err) {
                            if (err) {
                                console.error(err);
                                //don't return as we still need to release the connection
                            }

                            connection.release(function(err) {
                                if (err) {
                                    console.error(err);
                                    return;
                                }
                            });

                            callback(err); // We are done. We have committed all our things.
                        });
                    }
                }
            );
        });
    });
}

function mustBeCalledSecond() {
    console.log('doesn\'t matter what happens here');
}

**Comment by dmcghan** [comment] 2016-01-21 15:46
I just realized I was missed a release if there's an error with the execute:

```javascript
var oracledb = require('oracledb');
var fs = require('fs');

mustBeCalledFirst(myThings, function() {
    mustBeCalledSecond();
});

function mustBeCalledFirst(myThings, callback) {
    var myQuery = fs.readFileSync('some/path/to/a/file/where/i/have/a/query/saved.sql', 'utf8');

    oracledb.getConnection('MY CONNECTION DATA HERE', function(err, connection) {
        var numThings;

        if (err) {
            console.error(err);
            callback(err);
            return;
        }

        numThings = myThings.length;

        myThings.forEach(function(thing) {
            connection.execute(
                myQuery,
                {someBinding: thing.foo},
                function(err, result) {
                    if (err) {
                        console.error(err);
                        connection.release(function(err) {if (err) {console.err(err);}});
                        callback(err);
                        return;
                    }

                    numThings--;

                    if (numThings == 0) { // No more things left to insert into our db.
                        connection.commit(function(err) {
                            if (err) {
                                console.error(err);
                                //don't return as we still need to release the connection
                            }

                            connection.release(function(err) {
                                if (err) {
                                    console.error(err);
                                    return;
                                }
                            });

                            callback(err); // We are done. We have committed all our things.
                        });
                    }
                }
            );
        });
    });
}

function mustBeCalledSecond() {
    console.log('doesn\'t matter what happens here');
}
```

**Comment by grug** [comment] 2016-01-21 22:43
Hey @dmcghan 

Thanks for the response :) The problem here is that `err` is not set, even in the case of what I originally described. This definitely shouldn't be the case and ideally there would be some sort of error thrown.

-Dave

**Comment by dmcghan** [comment] 2016-01-21 22:47
Based on the code you posted, you wouldn't know if `err` was set because you're not checking it.

**Comment by grug** [comment] 2016-01-21 22:49
Hey @dmcghan,

Correct - the sample code I posted wouldn't know if `err` was set. However, I have tested with this and can assert that `err` isn't set in a fail case. I'm happy to post another set of code if you like, but I have a feeling you know what it's going to look like :P 

-Dave

**Comment by dmcghan** [comment] 2016-01-21 23:01
A reproducible test case would be a big help. Without it, there's not much we can do.

**Comment by grug** [comment] 2016-01-21 23:02
Sure - no worries. I'll get something together.

**Comment by grug** [comment] 2016-01-21 23:11
Actually on reviewing the code that you provided - that will cause the silent fail. Unfortunately I can't give you the schema, query being run and access to the database that I'm accessing... In the condition where a connection is still being executed and `connection.execute` is hit again, that is when things fall over. As I mentioned in the original post, I have already solved the problem in my code and I'm not actually facing any issues - I just think that it would be nice if the call didn't fail silently.

-Dave

**Comment by cjbj** [comment] 2016-01-21 23:41
@grug we can't fix something we can't reproduce.  Can you work on a testcase for us?

**Comment by forgotPassword** [comment] 2016-01-21 23:42
isn't the problem you are executing simultaneous queries on the same connection? where does it say the statements will be queued?

this is solvable using async lib, where you can use series/waterfall..

```

var se = [],
    db_con;

se.push(db.get_connection);

se.push(function(con, acb){
     db_con = con;
     acb(false);
});


for(let i=0;i<10;i++){ // or use closure
    se.push(function(acb){
        db_con.execute(.....,{x : obj[keys[i]]},  acb);
    });    
};

se.push(function(acb){
    db_con.commit(acb);
});

async.series(function(err){
    db_con.release();
});

```

**Comment by cjbj** [comment] 2016-01-21 23:44
@forgotPassword internally OCI should be locking.  But waterfall is better.

**Comment by grug** [comment] 2016-01-21 23:46
@cjbj I can work on something more elaborate over the weekend to better assist a fix.

@forgotPassword - once again - yes, this is solvable using an async lib (and I have already solved my problem). Yes, this is caused by executing simultaneous queries on the same question. I was just trying to point out that if this situation occurs, things fail silently.

**Comment by cjbj** [comment] 2016-04-15 02:03
Closing this old thread.  If a testcase is available, we can reopen it.

**Closed by cjbj** 2016-04-15 02:03 UTC
