### ISSUE TITLE
 NJS-040: connection request timeout

### ISSUE THREAD

**Issue by amateur-hkl** [oracle/node-oracledb#731] opened 2017-07-16 16:24 UTC
In my experiment I do one getConnection at init and keep using that one connection. At transaction end we do either COMMIT or ROLLBACK. This enables doing a large number of UPDATEs following at the end of one COMMIT. We will probala keep using that one connection until end of process lifetime.

The time interval between the UPDATEs may be very long.

autoCommit cannot be used for application reasons..

queueTimeout  is at default (60000)

When doing this I get a "Connection lost (NJS-040) every 62 seconds.

Stack trace when using most recent Node.js:

Uncaught exception  Error: NJS-040: connection request timeout

    at Pool.onRequestTimeout (.../oracledb/lib/pool.js:123:38)

    at Timeout._onTimeout (.../oracledb/lib/pool.js:181:28)

    at ontimeout (timers.js:488:11)

    at tryOnTimeout (timers.js:323:5)

    at Timer.listOnTimeout (timers.js:283:5)

Setting queueTimeout to 0 fixews the message, but will node then discover a unsuccesfull getConnection?

4. What is the version of Oracle Database?  12.1

5. What is your OS and version? UBUNTU 14

6. What compiler version did you use?  For example, with GCC, run `gcc --version`
  8 Something

7. What environment variables did you set?  How *exactly* did you set them?

NA

**Comment by dmcghan** [comment] 2017-07-16 16:45
@amateur-hkl I'm unable to reproduce with the following test:

```javascript
const oracledb = require('oracledb');
const config = require('./dbConfig.js');
const secondsToWait = 65;
let conn;

oracledb.getConnection(config)
  .then((c) => {
    conn = c;

    console.log('Got connection, waiting ' + secondsToWait + ' seconds to use it...');
  })
  .then(() => {
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve();
        console.log('Done waiting, proceeding to use the connection');
      }, secondsToWait * 1000);
    });
  })
  .then(() => {
    return conn.execute(
     `select *
      from dual`,
      [],
      {
        outFormat: oracledb.OBJECT
      }
    );
  })
  .then(result => {
    console.log(result.rows);
  })
  .catch(err => {
    console.log('Error in processing', err);
  })
  .then(() => {
    if (conn) { // conn assignment worked, need to close
      return conn.close();
    }
  })
  .catch(err => {
    console.log('Error during close', err);
  });
```

Could you please try that and let us know what you get?

**Comment by cjbj** [comment] 2017-07-17 00:47
> We will probala keep using that one connection until end of process lifetime.

This is not going to be a resilient architecture, as you have found out.  Even if your script works perfectly in normal conditions, it needs to cope with unexpected conditions.  If you have long periods where the script is inactive, waiting for some kind of input, then release the connection to the pool when you aren't using it.  This will let the pool handle reconnection in a number of cases.  (I recommend using the 12.2 client, which will work fine with your 12.1 DB).  You don't directly mention that you are using connection pooling, but the errors indicate you are.

> Setting queueTimeout to 0 fixews the message

If you are only using one connection, where does the queue come in?  

Setting this to 0 means that requests for connections may never be satisfied, so this will hide any problem.

If you are doing load testing with a bigger poolMax, have you [increased the number of threads](https://github.com/oracle/node-oracledb/blob/node-oracledb-v1/doc/api.md#numberofthreads) appropriately?

Check the[ pool stats](https://github.com/oracle/node-oracledb/blob/node-oracledb-v1/doc/api.md#connpoolmonitor) and see what is going on.

Seems like we don't know the whole story, so it is hard to comment on your best solution.

**Comment by amateur-hkl** [comment] 2017-07-17 08:08
Hi, I should perhaps frame the situation differently:

I guess that what you say is that 

 {
getConnection
   SELECT..
   SELECT..
   UPDATE A
   UPDATE B
   COMMIT
connection close
}

then the the updates to A and B are immortalised.

But if we have one or more clients, communicating over http with the nodejs server. Assume the clients need to do:
..
..
SELECT..
   User interaction
SELECT..
   User interaction
UPDATE A
   User interaction
UPDATE B
   User interaction
COMMIT or ROLLBACK // committing or not changes to A and B
..
..

and you expect each SQL Statement to act like this:

getConnection
  UPDATE A..
releaseConnection

which is not what I need, the COMMIT done later has no effect since the releaseConnection seems to imply a ROLLBACK.


But it is my understanding that the UPDATES are rolled back on closing or releasing the oracleDB connection

**Comment by dmcghan** [comment] 2017-07-17 16:05
@amateur-hkl I think I get what you're trying to do (but maybe not). With client/server style applications, users often have dedicated connections to the database. This provides an interesting level of control (similar to what you're describing), but it doesn't scale well as each connection requires its own process, memory, etc.

Modern applications typically use connection pools to do their work. You said a client needs to do these steps:

1. SELECT..
2. User interaction
3. SELECT..
4. User interaction
5. UPDATE A
6. User interaction
7. UPDATE B
8. User interaction
9. COMMIT or ROLLBACK // committing or not changes to A and B

Here's how I'd see that working transactionally with a connection pool:

1. SELECT.. (get connection from pool, select, close connection)
2. User interaction
3. SELECT.. (get connection from pool, select, close connection)
4. User interaction
5. UPDATE A (get connection from pool, update A)
7. UPDATE B (reuse open connection, update B w/autoCommit, close connection)
8. User interaction

The updates to A and B become a single unit of work. That requires that all the data for the changes to A and B be submitted to the web server at the same time.

You might ask, what happens if the data changes between the selects and the updates? This is where locking comes in and there are two basic types: optimistic and pessimistic. 

Client/server style apps that use dedicated connections would use pessimistic locking - where row-level locks are placed on the rows until a commit or rollback. Remember that with Oracle, readers don't block writers and writers don't block readers by default. The `select` statements would need to make use of the `for update` actually lock the rows. Again, this is rarely done for scalability reasons.

With optimistic locking, one assumes that "lost updates" would rarely occur (if ever) and an error is raised if it does. For this to work, the logic that does the updates must check to make sure the rows are in the same state from when the select was performed. There are various ways to do this. Some people use MD5 hashes of the row while others use a "version" column in each table that auto-increments with updates. MD5 hashes have a cost to compute but can't be "worked around". Version columns can scale better but could be worked around if the value is just sent out to the client (though that could be worked around).

Does any of that help or make sense?

If optimistic locking isn't sufficient, you might want to look into a feature of Oracle Database known as [Workspace Manager](https://docs.oracle.com/database/122/ADWSM/toc.htm). Workspace Manager allows you to version data, essentially, and one of its use case cases is to "Manage a collection of updates and insertions as a unit before incorporating them into production data".

**Comment by amateur-hkl** [comment] 2017-07-17 17:13
Hi and congratulations - you are spot on - except that between steps 5 and
6 there are (today at least) user interaction. No idea why.

As I see it, WEB-based client apps could not scale at all with my current
approach. Actually, I am misusing nodeJS. The benefit: The old version of
the app had OCI installed on each Client PC. With nodeJS/oracledb, the
client communicates with nodeJS over http/https; nodeJS is installed on or
close to the Oracle instance. The advantage is simpler client configuration
and other less important benefits.

And my experience with timeout happens in my context  -  (when user
interaction takes place between your steps 5 and 6 ).

Anyway - thanks for your time and competent advice! I am sure that
nodeJS/oracledb was not designed for my misuse, but I expect to be able to
get it to work. Just wanted to share my experience.




2017-07-17 18:24 GMT+02:00 Dan McGhan <notifications@github.com>:

**Comment by dmcghan** [comment] 2017-07-17 17:26
@amateur-hkl 

> except that between steps 5 and 6 there are (today at least) user interaction

It should be able to write the application in such a way that the user is able to do their flow in the client but the work is not submitted to the database until the final step.


> The advantage is simpler client configuration and other less important benefits.

How are you currently maintaining the relationship between client (web browser) and the database connection that they are using?


Finally, did you try running my test to see what happens?

**Comment by amateur-hkl** [comment] 2017-07-17 17:31
I shall test your sample tomorrow (and report), but I "know" it will work
OK since that is the way I started the development before it became clear
to me that I needed to keep a session in order to commit earlier updates...
And then I had no problems with timeout.




2017-07-17 19:28 GMT+02:00 Dan McGhan <notifications@github.com>:

**Comment by dmcghan** [comment] 2017-07-17 17:37
@amateur-hkl How are you currently maintaining the relationship between client (web browser) and the database connection that they are using?

**Comment by amateur-hkl** [comment] 2017-07-17 18:01
it is a traditional fat client

Am 17.07.2017 19:37 schrieb "Dan McGhan" <notifications@github.com>:

**Comment by dmcghan** [comment] 2017-07-17 18:03
@amateur-hkl Sorry, I'll rephrase...

How are you currently maintaining the relationship between fat client (which talks to Node.js over HTTPS) and the database connection that they are using?

**Comment by amateur-hkl** [comment] 2017-07-17 19:16
Up till now, each fat client has been Oracle-connected as "FC" using OCI
for the interface.

Currently, the tests has shown that nodeJS/oracledb fully can support one
fat client by maintaing one permanent session (i.e. Oracle connection).

The idea is for all fat clients to substitute https/nodeJS for the OCI
interface. The changes to the fat client are minimal and restricted to the
OCI-interface. The evaluation of this concept is ongoing.

Does this answer your question?


2017-07-17 20:08 GMT+02:00 Dan McGhan <notifications@github.com>:

**Comment by anthony-tuininga** [comment] 2017-07-17 19:32
I did something similar to this using Python and Django instead. Originally I had a fat client that connected directly to the Oracle database. When I replaced it with a connection to the Django web server I had to make sure that I sent all of the parts of the transaction at one time. Trying to keep the connection on the web server open while you do something on the fat client is asking for trouble! Thankfully, it wasn't too hard to adjust the fat client code to wait until it had everything needed for the transaction. I'd suggest you do the same!

**Comment by dmcghan** [comment] 2017-07-17 19:54
@amateur-hkl 

> The idea is for all fat clients to substitute https/nodeJS for the OCI interface.

I get that, but HTTP is stateless. So you're trying to link a stateless protocol to a stateful connection to the database. I'm just trying to figure out how you're doing this. 

If you have 10 clients and 10 connections, how do you route an incoming HTTP request to the correct database connection? How do you know when you need to open a connection to the database (when client-N first connects)? How do you know when to close a connection to the database (when client-N closes)? 

How long are you trying to keep connections open for?

**Comment by cjbj** [comment] 2017-07-17 20:27
In an HTTP world, an interesting technique is outlined in "Database Transactions Across Stateless Web Requests" on p230 of [The Underground PHP and Oracle Manual](http://www.oracle.com/technetwork/topics/php/underground-php-oracle-manual-098250.html).  This shows how to use DBMS_XA.  It's worth seeing whether this fits your requirements, or whether doing your own session caching is preferred.  Most web apps would do session caching of some sort so there is plenty of literature on it.

One still unexplained question:  did the queue use issue get resolved?

**Comment by amateur-hkl** [comment] 2017-07-17 21:02
well, I have not yet the complete answer, it is work in progress. And you
are right, it is a contrarian-concepts trial. I shall soon see. FYI, as I
could see so far, a COMMIT or a ROLLBACK signals the end of a transaction,
after that the session can be taken over by somebody else.



2017-07-17 21:54 GMT+02:00 Dan McGhan <notifications@github.com>:

**Comment by amateur-hkl** [comment] 2017-07-17 21:09
Hi

thanks, interesting reference.

I have not yet verified that the queue issue has been completely resolved,
but am now verifying performance and stability otherwise. It is still Work
In Progress.


2017-07-17 22:27 GMT+02:00 Christopher Jones <notifications@github.com>:

**Comment by dmcghan** [comment] 2017-07-17 21:37
@amateur-hkl 

> FYI, as I could see so far, a COMMIT or a ROLLBACK signals the end of a transaction, after that the session can be taken over by somebody else.

I can imagine some kind of wrapper module that has the following:
- A connections object/map that's used to map clientId's to connections in use.
- A startTransaction method. This would accept a clientId, pull a connection from the pool and add it to the map for the given clientId.
- An endTransaction method. This would commit or rollback the transaction, close the connection (put it back in the pool), and remove it from the map.
- An execute method that accepts the clientId so it can get the right connection from the map to do the work.

Be very careful with security in this model or it will be very easy for one client to fake another.

**Comment by cjbj** [comment] 2017-08-21 04:44
Closing - no update from user

**Closed by cjbj** 2017-08-21 04:44 UTC
Labels: question
