### ISSUE TITLE
undefined symbol: node_module_register

### ISSUE THREAD

**Issue by frenchbread** [oracle/node-oracledb#539] opened 2016-10-31 10:54 UTC
Related to #452.

#### Answer the following questions:

1. What error(s) you are seeing?

    ```
    Error: .../node_modules/oracledb/build/Release/oracledb.node: undefined symbol:  node_module_register
    ```

2. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?

    I am using oracledb within Node app with meteor.js framework.
    Running `$ meteor run` command which builds & launches the app,

3. What environment variables did you set?  How *exactly* did you set them?

    Using this env vars in `.zshrc`:
    ```
    export LD_LIBRARY_PATH=/opt/oracle/instantclient:$LD_LIBRARY_PATH
   export OCI_LIB_DIR=/opt/oracle/instantclient
   export OCI_INC_DIR=/opt/oracle/instantclient/sdk/include
   ```

    Checked that vars are loaded in terminal session - installation is ok.

4. What is your version of Node.js?

    Currently using node v7.0.0 (also tried with v6.9.1 and v4.2.3), npm v3.10.8 and latest oracledb.

5. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where it is installed?

     Installation of instant client went fine in general. Followed guide in [Install.md]   (https://github.com/oracle/node-oracledb/blob/master/INSTALL.md) for linux.
    Tried both instant client versions - latest v12.1.0.2.0 and v11.2.0.4.0.
    oracledb v1.11.0

6. What is your OS and version?

    Tried on macOs sierra 10.12, then switched to Ubuntu 16.10. Having same error on both systems

### Note
Interesting thing that previously everything worked. And as I recall, I had same issue, somehow fixed it and everything worked. I do system reset to factory settings regularly and after last "cleanup" it does not work.

**Comment by cjbj** [comment] 2016-12-08 00:34
Closing due to lack of updates.  Let me know if you found the cause.

**Closed by cjbj** 2016-12-08 00:34 UTC
Labels: Install & Configuration
