### ISSUE TITLE
Support for '?' as parameter placeholders in SQL strings

### ISSUE THREAD

**Issue by bagl** [oracle/node-oracledb#109] opened 2015-06-10 04:51 UTC
It is common to use **?** (question mark) characters in sql strings as placeholders in parametrized queries. Many SQL builders use that convention.

It would be nice if the driver handled this when parametrized query is used with positional parameters (provided via array).

**Comment by cjbj** [comment] 2015-06-10 05:39
We've discussed this in general for the underlying Oracle library, which is where it would need to be done. There have always been other priorities. I'll leave this open for a while to see what other people think so we can re-evaluate the current demands.

@bagl do you have a concrete example where you would use this in node-oracledb?

**Comment by alexsantos** [comment] 2015-06-11 17:59
Well, for me it would make things easier when migrating old code written in
Javascript/Rhino/Java to node-oracledb, where I have a lot of queries
written with '?' as a placeholder.

**Comment by cjbj** [comment] 2015-06-15 23:34
@alexsantos I agree it would be useful for migration.

Anyone got any interop examples, where the same code needs to run in multiple environments?
Details really help when trying to evaluate project impact.

**Comment by bagl** [comment] 2015-06-16 05:55
For example Squel.js expects prepared queries to have ? as placeholders. Sequelize.js deals with named parameters (not yet supporting oracle) but as a special case.

It is certainly no big issue and can be solved in thin wrapper on the client side. It would just make intergration with other tools a bit easier. If it's a non-trivial modification, it's not worth it.

And thanks for handling named parameters in the driver!

**Comment by dmcghan** [comment] 2015-06-17 14:40
It appears that sequelizejs builds out the query with the replacements in Node.js, prior to sending the query off for execution: 
http://docs.sequelizejs.com/en/latest/docs/raw-queries/

If I'm correct, that would be bad as it's not using bind variables which has both security and performance implications.

Here's an example they provide that uses a key syntax that at first glance appears to use bind variables (this syntax is supported in addition to the ? syntax which uses positional notation):
```javascript
sequelize.query('SELECT * FROM projects WHERE status = :status ',
  { replacements: { status: 'active' }, type: sequelize.QueryTypes.SELECT }
).then(function(projects) {
  console.log(projects)
})
```
The problem is that if the value of status changes for various executions, different queries would be sent to Oracle Database (if ever supported) and the optimizer would need to do multiple hard parses which, played out on a larger scale, could really impact performance. 

Also, while the node-oracledb driver doesn't support prepared statements, it does support statement caching which has a similar effect. However, improper use of bind variables will render that feature useless.

Here are some related sequalizejs issues:
https://github.com/sequelize/sequelize/issues/998
https://github.com/sequelize/sequelize/issues/1608

**Comment by cjbj** [comment] 2015-08-05 23:22
I'm going to close this but please add +1's if this is a real issue so we can track demand.

There are no plans to modify node-oracledb to parse SQL and convert '?' to ":name" bind syntax.  
It would need to be done in OCI; this would also make other C based language drivers (PHP, Perl, Python, Ruby etc) consistent.

**Closed by cjbj** 2015-08-05 23:22 UTC
Labels: wontfix

**Comment by jdmarshall** [comment] 2016-02-07 00:55
> The problem is that if the value of status changes for various executions, different queries would be sent to Oracle Database (if ever supported) and the optimizer would need to do multiple hard parses which, played out on a larger scale, could really impact performance.


@dmcghan I know we diagnosed precisely this issue on Oracle 9i and 10g a long time back, on an app using JDBC incorrectly.  Presumably it's still part of Oracle's query plan strategy, and bind variables scale to higher TPS.
