### ISSUE TITLE
Unhandled Exception when executing long-running stored procedure

### ISSUE THREAD

**Issue by Pusikas** [oracle/node-oracledb#774] opened 2017-10-20 12:37 UTC
I am using node 6.11.3 and node-oracledb 1.13.1. I use connection pools with the default settings. I can execute queries and stored procedures just fine. I check out a connection from the pool, run connection.execute() and then close the connection.

My problem is as follows: I execute like this:

```
connection.execute(...)
.then( ( result ) => {
  // do something with the results
} )
.catch( ( err ) => {
  // do something with the error
} );
```

I use a handler for uncaught exceptions that looks like this:
```
process.on( "uncaughtException", ( err ) => {
  console.log( err.message );
  console.log( err.stack );
  setTimeout( () => {
    process.exit();
  }, 500 );
} );
```
If I execute a stored procedure that takes more than 60 seconds to execute (it's buggy, shouldn't take this long, but that's not the point), then I get an unhandled exception after exactly 60 seconds:

```
"false == true"
AssertionError: false == true
        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1068:10)
```

It looks like connection.execute() never runs into the catch block in this case.

Where does this 60 second timeout come from? How would I correctly handle this kind of timeout? I know very well that this specific stored procedure is buggy (takes 2 minutes to fail and finish). But I find it confusing that I cannot catch this kind of error. Also, if the promise is never resolved or rejected, how can I close the connection to return it to the pool?

**Comment by dmcghan** [comment] 2017-10-20 16:57
@Pusikas What version of the database and what version of the OCI client are you using?

Please run a test to isolate the issue. Do this outside of your current application - just a single file, one-off test using no third-party modules other than the driver.

Connect to the database and invoke the buggy procedure, or (better yet) create a fake long-running proc using dbms_lock.sleep.

Test several times and let us know the results.

**Comment by Pusikas** [comment] 2017-10-20 21:55
Database runs 12.1.0.2, client libs should be instant client of the same version. Not at work atm, will try to isolate this on monday.

**Comment by cjbj** [comment] 2017-10-23 05:05
@Pusikas When you are creating a stand-alone test case, also try it [with node-oracledb v2](https://github.com/oracle/node-oracledb/issues/716).  I just pushed some updates to that branch, including "Check for JavaScript exceptions and if one is found, ensure that the error is passed correctly to the callback and is not raised when the C++ method has finished."  Whether this helps you, I can't tell without your test case.

**Comment by Pusikas** [comment] 2017-10-24 10:41
Okay, this looked easier than it is. First things first. I was wrong about the problem being a long-running operation. I cannot reproduce this with dbms_lock.sleep(). The problem seems to be an error that gets thrown in the stored procedure. It's an FTP upload that times out after 60 seconds because the IP address it tries to upload to exists, but does not accept connections on port 21.

I am still trying to write a small program to isolate this. My smallest attempts do not crash, but run into the catch instead - as they should. Using v2 does not seem to make a difference. It still crashes in my big program and does not crash in the smaller ones.

I am currently trying to slowly take away code until I reach the point where it no longer crashes, but this is tedious - especially since I have to wait 60sec for each attempt. 😬

So, nothing new to report atm, I am still trying to reduce this problem to a manageable size that I can easily share.

**Comment by dmcghan** [comment] 2017-10-24 16:08
@Pusikas Thanks for the update - glad to hear you couldn't reproduce with the test case on a long-running proc.

Does sound tedious... Good luck tracking it down!

**Comment by cjbj** [comment] 2017-12-14 10:53
Closing - no update.

**Closed by cjbj** 2017-12-14 10:53 UTC
Labels: question
