### ISSUE TITLE
Oracle Admin and OracleDB do not mix

### ISSUE THREAD

**Issue by chevalierc** [oracle/node-oracledb#527] opened 2016-10-13 16:15 UTC
I have had this issue which is solved by simply uninstalling oracle admin 11.2.0.4 64bit

When I have the Oracle Oracle Admin installed I receive this error:

```
Error: The specified procedure could not be found.
\\?\C:\working\synthetic_route_tool\node_modules\oracledb\build\Release\oracledb
.node
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\working\synthetic_route_tool\node_modules\oracledb
\lib\oracledb.js:35:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
```

I am running node v4.5.0 on windows10 64bit

I have competently moved all the oracleDB Instant Clients to there own folder for my last attempt. I corrected the environmental variables path, OCI_INC_DIR, OCI_LIB_DIR to reflect the path

When I install I don't receive any errors or information different from installing with Oracle Admin uninstalled

I delete the whole oracledb directory from my node modules directory before installing.

I install oracledb with administrative rights

Here is the gist of my [install](https://gist.github.com/chevalierc/7cc5787285deef500dfff5503a3ebe46)

**Comment by chevalierc** [comment] 2016-10-13 16:17
the file : `working\synthetic_route_tool\node_modules\oracledb\build\Release\oracledb
.node` is present

**Comment by dmcghan** [comment] 2016-10-14 14:09
What is "Oracle Admin"?

**Comment by cjbj** [comment] 2016-10-19 00:37
The cause sounds like an Oracle client library version clash.

**Comment by cjbj** [comment] 2017-01-10 04:53
Closing - no updates

**Closed by cjbj** 2017-01-10 04:53 UTC
Labels: Install & Configuration

**Comment by chevalierc** [comment] 2017-01-10 15:26
sorry, I couldn't figure out exactly what was. It was through my employers software portal and no one could quite tell me.

**Comment by cjbj** [comment] 2017-01-11 00:13
@chevalierc that must be annoying.  Did you check @bchr02's work in #18?
