### ISSUE TITLE
Need to disable Connection Pool pinging with Oracle DB 9i to resolve DPI-007

### ISSUE THREAD

**Issue by slewis30328** [oracle/node-oracledb#625] opened 2017-02-20 19:50 UTC
Was wondering if there are any known issues regarding the connection pool feature in oracledb against a 9i instance?  I don't have any issues connecting to 9i if I don't use the pool.  When using the pool, the connections are created at startup, but when the getConnection method is called, it looks like it makes continuous calls to get a handle and then eventually runs out of resources and stops.  I watch v$sssion to see what's going on.  The error that is eventually returned is: DPI-007: invalid OCI handle or descriptor.  I'm using oracledb version 1.12.2 and instant client 11.2.0.1.0. Any help would be appreciated. Thanks.

**Comment by cjbj** [comment] 2017-02-21 18:59
No known issues but we have focused on active versions of the DB.  Is it just an application problem - are you correctly releasing connections in all code paths?  What does the pool queue show?  If you set poolMin to be the same as poolMax (and set poolIncrement to 0) so that all connections are opened at pool creation time, does your DB cope with this number of connections?

**Comment by slewis30328** [comment] 2017-02-21 20:41
Just in testing/research mode right now - not an application yet.  Would like to use Node on a new project and seeing if it will work on 9i - wish I could upgrade but I have to live with 9i for now (long story).  I'm running the webapp.js to test. Located in oracledb examples directory.  I played with the config you suggested and still got same behavior.  Error occurs on line 107.  Same message every time: getConnection() error: DPI-007: invalid OCI handle or descriptor. BTW, if I begin with poolMin > 0 the connections are created - see in v$session. Problem surfaces when I try to grab one of those connections from pool.  Thanks for looking into this...

**Comment by cjbj** [comment] 2017-02-24 01:54
@slewis30328 I checked with a developer; the error wasn't expected.  Check you really are building & running with the same 11.2 client.  Also, why not use the most recent 11.2.0.4 Instant Client?

**Comment by cjbj** [comment] 2017-03-01 22:12
Since [12.2 got released](https://sqlmaria.com/2017/03/01/oracle-database-12c-release-2-available-everywhere/) today, 9iR2 is now  7 major release of Oracle ago, and well out of support. I've been futzing around trying to resurrect old OS versions and install 9.2 but without luck - I keep finding I need older stuff than I have.  I suspect my current, in-progress install will fail to complete since it is throwing JNI errors.  (I'm glad recent installs are so much better, specially with XE RPMs, or the EE [preinstall scripts](https://docs.oracle.com/database/121/LADBI/olinrpm.htm#LADBI7480)).

**Comment by slewis30328** [comment] 2017-03-03 01:34
Chris,

Thanks for trying.  I realize 9i is ancient.  Might just have to wait 
until my company can upgrade our instances.  It was looking promising 
until I tried using the pool.  I really need a connection pool for a 
production deployment.  If you find anything out, please pass on.

Steve

------ Original Message ------

**Comment by cjbj** [comment] 2017-03-03 03:30
@slewis30328 I'll keep asking around to try and find a 9.2 DB; the error wasn't expected.  It would be good to know the cause.

**Comment by slewis30328** [comment] 2017-03-11 22:52
Hey Chris,

Still trying to figure out this issue with 9i.  I really want to use 
this driver on a new project, but I have to get the pooling to work.  Is 
there any debugging/dumps/traces I can turn on that would help you 
figure this out?  Doesn't seem to make sense why I can get a connection 
without the pool, connections are created when the pool starts up, but 
every time I try to get a connection from the pool with getConnection I 
get the OCI error: DPI-007: invalid OCI handle or descriptor.  Do you 
work for Oracle? Also, if I were able to get you connected to our 9i 
instance would that help?

Thanks much...

Steve

------ Original Message ------

**Comment by cjbj** [comment] 2017-03-12 10:39
@slewis30328 I've been busy with the Oracle DB 12.2 release and with https://github.com/oracle/python-cx_Oracle (and some travel).

**Comment by cjbj** [comment] 2017-03-14 05:14
@slewis30328 (or anyone else with this issue) what is your exact version of the 9i database?

**Comment by slewis30328** [comment] 2017-03-14 13:57
Chris:

Oracle 9i version is: 9.2.0.7

Thanks again for looking into this!

------ Original Message ------

**Comment by jcallison70** [comment] 2017-03-14 14:38
I am having the exact same issue: "DPI-007: invalid OCI handle or descriptor" error when connecting to a 9i database through a pool. The workaround for me was to roll back to version 1.11.0 of node-oracledb. Something between 1.11.0 and 1.12.2 broke 9i support.

In case someone is interested, here are the versions involved for the working system:
Oracle 9i version 9.2.0.8.0
Oracle Instant Client version 11.2.0.4.0
Node version 6.10.0 (32-bit)
node-oracledb version 1.11.0
Windows 7 (64-bit)

**Comment by slewis30328** [comment] 2017-03-14 14:59
That's good to know.  Thought I might be the problem.  I will try rolling back today and see if pooling works.  I have a very similar config:

Oracle 9i version 9.2.0.7
Oracle Instant Client version 11.2.0.4.0
Node version 7.5.0 (64-bit)
node-oracledb version 1.12.2
Windows 7 (64-bit)

Thanks for the post Jerry!

**Comment by cjbj** [comment] 2017-03-14 21:29
@slewis30328 with the info from @jcallison70, one quick thing to check is to set oracledb.poolPingInterval to a negative value
https://github.com/oracle/node-oracledb/blob/v1.12.2/doc/api.md#propdbpoolpinginterval

**Comment by slewis30328** [comment] 2017-03-15 00:35
Chris,

Just a heads up.  Set poolPingInterval = -1 and the pool is now working. 
  Wow.  Some serious hours wasted in the last month trying to figure this 
out.  Not sure what a negative value is doing...I guess negating the 
check to see if the pool conn is alive/valid? Anyway, thanks for all 
your help.  I'm going with this for now!

Steve


------ Original Message ------

**Comment by cjbj** [comment] 2017-03-15 01:32
@slewis30328 your persistence with this is appreciated.

**Comment by cjbj** [comment] 2018-02-21 10:35
@slewis30328 did you ever test node-oracledb 2?  I suspect the problem will still exist, but since the lower DB access layer changed in v2, there is a small possibility it was fixed.

**Comment by slewis30328** [comment] 2018-02-23 15:08
I have upgraded to 2 and no longer need to set poolPingInterval to -1.  So, yes, problem has been fixed.  We are in process of upgrading to 12C so issue went on back-burner.  Thanks for checking up.  BTW, V2 is working great.

**Comment by cjbj** [comment] 2018-03-01 05:48
@slewis30328 (apologies I got sidetracked) Excellent and thanks for the feedback.  I'll close this issue.

**Closed by cjbj** 2018-03-01 05:48 UTC
Labels: bug
