### ISSUE TITLE
Process finished with exit code -1073740791 (0xC0000409)  

### ISSUE THREAD

**Issue by ccrop** [oracle/node-oracledb#954] opened 2018-07-31 01:51 UTC
Overview
     A simple application, when the query is executed continuously, the application collapses and exits after repeated cycles.

//program code begin
var oracledb = require('oracledb');
oracledb.autoCommit = true;
function doRelease(connection) {
    connection.close(
        function(err) {
            if (err)
                console.log("1",err.message);
        });
}
let query = function (sql, params, callback) {
    oracledb.getConnection(  // gets a connection from the 'default' connection pool

        {
            user: "bd_lbs",
            password: "bd_lbs",
            connectString:"127.0.0.1:1521/orcl"
        },
        function (err, connection) {
            if (err) {               
                if (typeof callback == 'function')
                    callback(err, null);

                return;
            }
            connection.execute(sql, params,
                function (err, result) {
                    if (err) {                        
                        if (typeof callback == 'function')
                            callback(err, null);
                        doRelease(connection);
                        return;
                    }
                    if (typeof callback == 'function')
                        callback(err, result.rows);
                    doRelease(connection);

                });
        });
}

let getMyMessage = function (userid,callback) {

    let sql = "select * from aa" ; //any table
    let para = []   
    query(sql,para,(err,rows)=>{
        if(err){
            if (typeof callback == 'function')
                callback(err,null);
            return;
        }
        if(rows.length>0)
        {
            if (typeof callback == 'function')
                callback(err,rows);
        }
        else
        {
            if (typeof callback == 'function')
                callback("err",null);
        }

    })
}

let t = 1
setInterval(()=>{
    getMyMessage(52)
    getMyMessage(52) //Key Point
    console.log(t)
   t++
    //-------------------------
},100)
//code end

//log ：After 200 cycles，Process finished with exit code -1073740791 (0xC0000409)

Answer the following questions:
What is your Node.js version? Is it 64-bit or 32-bit? Run version.js from
Nodejs v10.5.0 or v8.9, 64-bit.

What is your node-oracledb version?
v2.3.0

What is your Oracle client (e.g. Instant Client) version? Is it 64-bit or 32-bit? How was it installed? Where is it installed?
12.2.0.1.0-1, 64-bit, installed from windows oracle12C,windows install

What is your Oracle Database version?
Oracle Database 12c - 64bit or  Oracel Database 10.0.2

What is your OS and version?
windows10 64bit or windows2008 64bit

What is your compiler version? For example, with GCC, run gcc --version
4.9.2

What Oracle environment variables did you set? How exactly did you set them?
PATH=D:\oracle\product\12.2.0\dbhome_1\bin, my oracle database is on localhost side.

What is the PATH environment variable (on Windows) or LD_LIBRARY_PATH (on Linux) set to? On macOS, what is in ~/lib?
PATH=D:\oracle\product\12.2.0\dbhome_1\bin

What exact command caused the problem (e.g. what command did you try to install with)? Who were you logged in as?
in nodejs script

What error(s) you are seeing?
Process finished with exit code -1073740791 (0xC0000409)

**Comment by cjbj** [comment] 2018-07-31 02:08
This is a duplicate of #941 isn't it? Thanks for filling in the template this time but you still missed https://help.github.com/articles/creating-and-highlighting-code-blocks/ !! :)

What have you tried instead?  What debugging have you done?  Memory issues?  DB resource issues?  What about using async/await instead of callbacks? 

I see the code comment about using a connection pool however the code is using standalone connections instead.

More importantly, before digging into the code, what is the actual goal - why is it trying to 'loop'?

**Comment by ccrop** [comment] 2018-07-31 02:43
Thank you very much for your quick reply. Please switch to windows for testing, and select complex table queries. I cycle 500 times or so to quit.

**Comment by cjbj** [comment] 2018-07-31 03:01
I'm not a Windows user.  Please switch to Linux to test. :)

But seriously, if you were having issues with connection pooling then you may have some conceptual issues that further experimentation and practice will help you with.  Try the async/await approach.  Check on using CQN.   Sorry I dont' have time to dig into code at the moment.

**Comment by ccrop** [comment] 2018-07-31 03:24
I'll try the way you say.Thank you very much.

**Comment by danilohgds** [comment] 2018-07-31 03:30
@ccrop 
I'm going to go with @cjbj on this one, and give you the general "review and experiment" answer. I ran your code on a Windows 10 Pro Machine, decent specs.

At some point during the execution, the memory allocation from the RDBMS Kernel reached over 90% of the total memory available on my system. Your code is not closing the connections. 

https://imgur.com/a/kprQrq0

The first thing I would do in your place is to switch back to the connection pool. There are but very few scenarios where connection pool is not advisable, the overhead involved in getting that new connection is greater than you think.

If you have trouble with async patterns and proper connection management, follow this up: https://jsao.io/2017/06/how-to-get-use-and-close-a-db-connection-using-various-async-patterns/

Best of luck

**Comment by cjbj** [comment] 2018-08-03 23:55
Closing this.  Let us know if the examples that @danilohgds pointed you to don't help.

**Closed by cjbj** 2018-08-03 23:55 UTC
Labels: question
