### ISSUE TITLE
Cannot POST/

### ISSUE THREAD

**Issue by Karthick3** [oracle/node-oracledb#926] opened 2018-06-13 09:34 UTC

**Comment by Karthick3** [comment] 2018-06-13 09:37
Hi
I got cannot post/ error while i submit in html page
Here is my script

app.get('/index', function (req, res) {

   res.sendFile( __dirname + "/" + "index.htm" );
  // app.use(express.static(__dirname, { index: 'index.htm' }));
})
app.post('/process_post', function (req, res) {
console.log("contenttype"+req.get('Content-Type'))
  
  doGetConnection(res, function(err, connection) {
    if (err)
      return;
    connection.execute(
      "INSERT INTO TEST_TABLE(FIRST_NAME,LAST_NAME) VALUES ('xxxx','yyy')",
//	[req.body.FIRST_NAME,req.body.LAST_NAME ],
   //  { s: JSON.stringify(req.body),  p: JSON.stringify(req.body)},
	 
      { autoCommit: true,
	  outFormat:oracledb.OBJECT
	  },
	   console.log("check2"),
      function (err) {
	  console.log("check3");
        if (err) {
		console.log("check4");
          res.set('Content-Type', 'application/json');
          res.status(400).send(JSON.stringify({
            status: 400,
            message: "Input Error",
            detailed_message: err.message
          }));
        } else {
		 console.log("check3");
          // Successfully created the resource
          res.status(201).set('Location', '/process_post/'+req.body.FIRST_NAME).end();
		  
        }
        doRelease(connection, "POST /process_post");
      });
  });
});


HTML SCRIPT
<html>
   <body>
      
      <form action = "/process_post" method = "POST">
         First Name: <input type = "text" name = "first_name">  <br>
         Last Name: <input type = "text" name = "last_name">
         <input type = "submit" value = "Submit" >
      </form>
      
   </body>
</html>

**Comment by cjbj** [comment] 2018-06-13 10:58
[It would help if you could edit your post and use Markdown for the code.  See https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code]

What is the symptom of the problem?  Is there an error?

Is this a duplicate of https://community.oracle.com/message/14844371#14844371 ?

Can you try doing some experimenting and debugging?

**Comment by Karthick3** [comment] 2018-06-13 11:18
Hi CJ,
I tried but still a got error.

**Comment by Karthick3** [comment] 2018-06-13 11:22
Hi CJ,
You saw the link but not responding to that.I hope community is helping others problem.
https://community.oracle.com/message/14844371#14844371

**Comment by cjbj** [comment] 2018-06-13 23:33
@Karthick3 maybe you could give some more info?  See my earlier questions.

**Comment by dmcghan** [comment] 2018-06-23 13:51
@Karthick3 I answered your question in the other thread, but I'll answer it here too...

Unless I'm misreading your code, you are calling `connection.execute` and passing 7 parameters:

- "INSERT INTO TEST_TABLE VALUES (:s,:p)"
- { s: JSON.stringify(req.body) }
- { p: JSON.stringify(req.body) }
- console.log("check1")
- { autoCommit: true }
- console.log("check2")
- function (err) {...

The first parameter, the insert statement, is correct, but the others are not. Please review the [API doc on conn.execute](https://oracle.github.io/node-oracledb/doc/api.html#execute) to understand the correct number and types of parameters to pass.

**Comment by cjbj** [comment] 2018-06-24 23:44
@Karthick3 take a look at the node-oracledb examples and make sure you can run them: https://github.com/oracle/node-oracledb/tree/master/examples

**Comment by dmcghan** [comment] 2018-06-25 17:51
@Karthick3 

> Can you fine tune the code and send me here.

No. We're not in the habit of doing people's homework for them. :) You should look at the [doc on `execute`](https://oracle.github.io/node-oracledb/doc/api.html#-426-connectionexecute), a [simple example](https://github.com/oracle/node-oracledb/blob/master/examples/select1.js), or perhaps at [this series](https://jsao.io/2018/03/creating-a-rest-api-with-node-js-and-oracle-database/).

I will help you, but you have to put in effort too. 

Here are two questions you need to be able to answer:

1. In the current code, when you call `connection.execute`, how many parameters do you pass?
2. What are the correct number and types of parameters you can pass to `connection.execute`?

Once you can answer those questions, try adjusting the code accordingly. Post your updated code so we can see your progress and guide you further. But please read up on properly displaying code in GitHub when you do post it: [https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code)

**Comment by cjbj** [comment] 2018-07-15 01:17
Closing - no update.

**Closed by cjbj** 2018-07-15 01:18 UTC
Labels: question
