### ISSUE TITLE
NJS-40. Connection pool does not increase after a while

### ISSUE THREAD

**Issue by tirdman** [oracle/node-oracledb#1295] opened 2020-09-11 07:28 UTC
1. What versions are you using?

db Version
Oracle 11g

process.platform
linux

process.version
v8.9.1

process.arch
x64

require('oracledb').versionString
3.1.2

require('oracledb').oracleClientVersionString
12.2.0.1.0

2. Describe the problem

My application is NodeJs + Express. 

Recently a problem began to appear. I can't say what has changed in the application. The application can work normally for about a day, but then the NJS-40 error starts to appear. It is impossible to repeat the problem on purpose, it occurs periodically. I tried different pool settings: same poolMin, poolMax, UV_THREADPOOL_SIZE and others. I studied various queries on the NJS-40 topic, but I still can't solve the problem.
I tried the last settings like this:
Pool statistics ...
... total up time (milliseconds): 6178890
... total connection requests: 25244
... total requests enqueued: 1107
... total requests dequeued: 533
... total requests failed: 0
... total request timeouts: 485
... max queue length: 126
... sum of time in queue (milliseconds): 29186339
... min time in queue (milliseconds): 0
... max time in queue (milliseconds): 4303
... avg time in queue (milliseconds): 26365
... pool connections in use: 0
... pool connections open: 30
Related pool attributes:
... poolAlias: default
... queueTimeout (milliseconds): 60000
... poolMin: 30
... poolMax: 30
... poolIncrement: 0
... poolTimeout (seconds): 0
... poolPingInterval: 60
... stmtCacheSize: 30
Pool status:
... status: 6000
Related environment variables:
... process.env.UV_THREADPOOL_SIZE: 30

That is, the queue starts to accumulate while "pool connections in use" is 0 and poolMax is not exhausted.

I tried the option of additional logging in the settings:
..poolMin: 0
... poolMax: 75
... poolIncrement: 5
... poolTimeout (seconds): 3600
... poolPingInterval: 60.

Every 250 ms I requested truncated statistics in the format:
total connection requests | total requests enqueued | total requests dequeued | pool connections in use | pool connections open.

In such situations, at some time the pool stopped growing, although the stock was still there. After 20 hours of operation, the application first slipped one request into the queue:

loApi. PID: 23052.2020.09.11 12:22:08
54232 | 0 | 0 | 2 | 6
loApi. PID: 23052.2020.09.11 12:22:10
54232 | 0 | 0 | 0 | 6
loApi. PID: 23052.2020.09.11 12:22:10
54239 | 1 | 1 | 0 | 6
.
.
loApi. PID: 23052.2020.09.11 12:22:53
54299 | 1 | 1 | 3 | 6
loApi. PID: 23052.2020.09.11 12:22:53
54301 | 2 | 2 | 2 | 6
.
.
loApi. PID: 23052.2020.09.11 12:23:26
54352 | 2 | 2 | 0 | 6
loApi. PID: 23052.2020.09.11 12:23:27
54358 | 3 | 3 | 1 | 6
.
.
loApi. PID: 23052.2020.09.11 12:27:09
54737 | 3 | 3 | 1 | 6
loApi. PID: 23052.2020.09.11 12:27:10
54744 | 4 | 4 | 0 | 6

And at some point, the application completely stops processing requests and only the queue grows, although pool connections in use: 0.

loApi. PID: 23052.2020.09.11 12:36:41
55827 | 92 | 89 | 1 | 6
.
.
loApi. PID: 23052.2020.09.11 12:45:15
56221 | 486 | 89 | 0 | 6
loApi. PID: 23052.2020.09.11 12:45:15
56222 | 487 | 89 | 0 | 6
loApi. PID: 23052.2020.09.11 12:45:15

Moreover, the application is launched in cluster mode with 6 processes and the other problems have not been observed for some time. But it will go down for a while and the others will have the same problem.

**Comment by cjbj** [comment] 2020-09-11 07:37
- What was the app state when you got the stats?  Was the pool usable or were you getting NJS-040's?

- Show us details about how your application is actually run, e.g. prove to us that UV_THREADPOOL_SIZE is set in the correct location.  It's easy to get this wrong.

- examine your app code flow and make sure you are releasing connections back to the pool.  The pool implementation's been pretty solid since queuing was added.

- The log output you showed had min=max, so the pool is a fixed size.  You only had a few connections go into the pool queue, so your pool is probably (for this particular scenario) too big.  Check your actual apps logs and see whether you can reduce it. (This is not related to your issue)

- Your tech stack is "old" :)

**Comment by tirdman** [comment] 2020-09-11 08:12
> Your tech stack is "old" :)
This is true :) The application is several years old and the load on it is growing due to the introduction of new functionality. Do you think updating the version of nodejs and the oracledb library can fix the problem?

> What was the app state when you got the stats? Was the pool usable or were you getting NJS-040's?
Statistics through setInterval function continued to be written to the file. And requests from the ExpressJS API returned NJS-040.

>Show us details about how your application is actually run, e.g. prove to us that UV_THREADPOOL_SIZE is set in the correct location. It's easy to get this wrong.
The application is launched via PM2 with the following configuration section:
{
     name: 'loApi',
     script: 'app.js',
     node_args: ['--max_old_space_size = 6144'],
     out_file: '/ dev / null',
     error_file: '/ dev / null',
     instances: 6,
     exec_mode: 'cluster',
     env: {
     UV_THREADPOOL_SIZE: 30,
     processName: 'loApi',
     }

> examine your app code flow and make sure you are releasing connections back to the pool. The pool implementation's been pretty solid since queuing was added.
After making requests, I use the close () function. And I have no problem with "pool in use" overflow. At the moment when growth is needed, the "pool in open" is much less than poolMax. This was shown in the first post.

>The log output you showed had min=max, so the pool is a fixed size. You only had a few connections go into the pool queue, so your pool is probably (for this particular scenario) too big. Check your actual apps logs and see whether you can reduce it. (This is not related to your issue)
Right. It is very rare when I need more than 12 simultaneous connections. But I tried different options with the same sizes 10. And 15. But after some time the queue starts to accumulate, although the "pool in use" in the logs is small: for example, 1-4.
Here is an example of statistics when 297 requests were processed in a minute and 2 of them got into the queue

Pool statistics ...
... total up time (milliseconds): 5038409
... total connection requests: 21778
... total requests enqueued: 0
... total requests dequeued: 0
... total requests failed: 0
... total request timeouts: 0
... max queue length: 0
... sum of time in queue (milliseconds): 0
... min time in queue (milliseconds): 0
... max time in queue (milliseconds): 0
... avg time in queue (milliseconds): 0
... pool connections in use: 1
... pool connections open: 30
Related pool attributes:
... poolAlias: default
... queueTimeout (milliseconds): 60000
... poolMin: 30
... poolMax: 30
... poolIncrement: 0
... poolTimeout (seconds): 0
... poolPingInterval: 60
... stmtCacheSize: 30
Pool status:
... status: 6000
Related environment variables:
... process.env.UV_THREADPOOL_SIZE: 30

...
...

Pool statistics ...
... total up time (milliseconds): 5098410
... total connection requests: 22075
... total requests enqueued: 2
... total requests dequeued: 2
... total requests failed: 0
... total request timeouts: 0
... max queue length: 1
... sum of time in queue (milliseconds): 20
... min time in queue (milliseconds): 0
... max time in queue (milliseconds): 18
... avg time in queue (milliseconds): 10
... pool connections in use: 1
... pool connections open: 30
Related pool attributes:
... poolAlias: default
... queueTimeout (milliseconds): 60000
... poolMin: 30
... poolMax: 30
... poolIncrement: 0
... poolTimeout (seconds): 0
... poolPingInterval: 60
... stmtCacheSize: 30
Pool status:
... status: 6000
Related environment variables:
... process.env.UV_THREADPOOL_SIZE: 30

After a while, the queue began to fill up quickly, although the "pool in use" is still small:

Pool statistics ...
... total up time (milliseconds): 5578414
... total connection requests: 24115
... total requests enqueued: 297
... total requests dequeued: 297
... total requests failed: 0
... total request timeouts: 0
... max queue length: 6
... sum of time in queue (milliseconds): 50299
... min time in queue (milliseconds): 0
... max time in queue (milliseconds): 4303
... avg time in queue (milliseconds): 169
... pool connections in use: 0
... pool connections open: 30
Related pool attributes:
... poolAlias: default
... queueTimeout (milliseconds): 60000
... poolMin: 30
... poolMax: 30
... poolIncrement: 0
... poolTimeout (seconds): 0
... poolPingInterval: 60
... stmtCacheSize: 30
Pool status:
... status: 6000
Related environment variables:
... process.env.UV_THREADPOOL_SIZE: 30
...
...
Pool statistics ...
... total up time (milliseconds): 6178890
... total connection requests: 25244
... total requests enqueued: 1107
... total requests dequeued: 533
... total requests failed: 0
... total request timeouts: 485
... max queue length: 126
... sum of time in queue (milliseconds): 29186339
... min time in queue (milliseconds): 0
... max time in queue (milliseconds): 4303
... avg time in queue (milliseconds): 26365
... pool connections in use: 0
... pool connections open: 30
Related pool attributes:
... poolAlias: default
... queueTimeout (milliseconds): 60000
... poolMin: 30
... poolMax: 30
... poolIncrement: 0
... poolTimeout (seconds): 0
... poolPingInterval: 60
... stmtCacheSize: 30
Pool status:
... status: 6000
Related environment variables:
... process.env.UV_THREADPOOL_SIZE: 30

The last statistic shows a case when connections stop processing altogether and the application has to be restarted.

**Comment by cjbj** [comment] 2020-09-16 12:10
@tirdman how's this going?

It seems like your app isn't returning connections to the pool.

Upgrading the app stack would be interesting, but there's nothing definitive that I can say about the impact it would have on your problem.  

Are you using DRCP?

I think running 'pstack' on a hung process might be the next thing we can look at.  We can talk offline if you don't want to host the trace publicly.

**Comment by tirdman** [comment] 2020-09-17 01:48
@cjbj nothing good.

>It seems like your app isn't returning connections to the pool.

I expected the "pool in use" to increase in this case. But it doesn't happen for me. Is not it?

> Upgrading the app stack would be interesting, but there's nothing definitive that I can say about the impact it would have on your problem.

I will do this in October 2020.

> Are you using DRCP?

I am not a database administrator. My colleagues provided it to me. I just use a prepared database environment and perform CRUD operations. I do not do anything special on the side of the application.

> I think running 'pstack' on a hung process might be the next thing we can look at. We can talk offline if you don't want to host the trace publicly.

Never worked with 'pstack'. Does the program run on the database server? Can you tell me how to act?

**Comment by cjbj** [comment] 2020-09-17 01:58
Can you find out about DRCP?

Are you seeing any 'client side' trace files? 

Is there any network issue (or config change) that is causing something to hang?

pstack is a system command.  Find a hung process and run 'pstack <pid>' - but check the man page for details.

I'd like to get this solved for you.

**Comment by tirdman** [comment] 2020-09-17 04:39
I'll do a few more checks and give feedback later.

**Comment by cjbj** [comment] 2020-09-17 04:46
Has the app been idle for a while before you see this?

**Comment by tirdman** [comment] 2020-09-17 05:25
At the moment, I have configured the automatic restart of the application when I receive an NJS-40 error (queueTimeout 5 seconds, so that it is less noticeable to users). This happens approximately once a day.
I set up additional logging for api requests and noticed that after some requests, sessions become "dead", that is, sessions are never started again (using a special table provided by the database administrators). I want to additionally check these routes for whether the session is closed after the SQL query.
Is it possible that the connection is actually open (the close () function has not been executed), but it is not included in the "pool in use" statistics?

**Comment by cjbj** [comment] 2020-09-17 09:42
When does it happen - during idle time?  

I don't have any good hypothesis; need more info.

I guess it doesn't help pointing out that many other people are using node-oracledb OK!! :)

**Comment by tirdman** [comment] 2020-09-23 05:25
@cjbj Of course oracledb is a awesome library.
I found the problem, it is simple.
In one new route, the express API did not close the database connection.
But I still do not understand why in the statistics the "pool in use" counter did not increase to the maximum, but the queue grew. Precisely because of this I got confused.

**Comment by cjbj** [comment] 2020-09-23 06:26
That's good news.  What kind of scoping existed (let, var, const) were you using for the connection and what scope? 

We'll have a brains-trust discussion on this and review the code.  I could possibly, maybe, almost conceive the C & Node layer attrs getting out of sync, but the pool InUse and Open attrs are both from the C layer.

**Comment by tirdman** [comment] 2020-09-24 01:47
An example function code is shown below. Previously missing "finally" block

const findByVnAccount = async params => {
  let connect;

  try {
    connect = await oracledb.getPool().getConnection();

    let q = `SELECT SYSDATE FROM DUAL`;

    let result = await connect.execute(q, [], {
      outFormat: oracledb.OBJECT,
    });

    return result;
  } catch (e) {
    throw new Error(`Some broke: ${e}`);
  } finally {
    try {
      await connect.close();
    } catch (e) {
      console.log(`Error closing connection: ${e}`);
    }
  }
};

**Comment by cjbj** [comment] 2020-09-25 00:47
@tirdman in a review there was nothing obvious jumping out.  More info would be needed.  I.e. it would be nice to know more about the state at the time of the 'hang'.

- What is the state of connections shown in V$SESSION at time of hang?
- If the app was run with DPI_DEBUG_LEVEL to 4, we could see if the C layer was involved
- Upgrading node-oracledb might have a different behavior due to the refactoring; but nothing definite could be identified.
- We will add _connectionsOut to the _logStats output to check whether the Node.js layer and C layers are in sync.

Since you have fixed your root cause, I understand you may not want to spend time on this.

**Comment by tirdman** [comment] 2020-09-25 11:11
Christopher, you are absolutely right. Unfortunately, I don't have time to dive deeply into debugging right now.
I am very grateful to you for your professional advice!
Your answer, "It seems like your app isn't returning connections to the pool." made me think to study all the innovations in the code, where I found the error. Thanks again!

**Comment by cjbj** [comment] 2020-09-28 11:11
@tirdman I'll close this issue but will keep it in mind.

**Closed by cjbj** 2020-09-28 11:11 UTC
Labels: question
