### ISSUE TITLE
NJS-012 when insert values with date and returning

### ISSUE THREAD

**Issue by mynoheart** [oracle/node-oracledb#121] opened 2015-06-19 09:39 UTC
Hello.
```js
oracledb.getConnection({
    user          : dbConfig.user,
    password      : dbConfig.password,
    connectString : dbConfig.connectString
}, function(err, con) {
  var table = 'create table test_binds ( num number(4), str varchar2(32), dt date )';
  con.execute(table, function(err) {
    if (err) { return console.log(err.message); }
    var insert = 'insert into test_binds (num, str, dt) values (:num, :str, :dt)';
    var params = {
      num: 123,
      str: 'str',
      dt: new Date()
    };
    console.log('insert ok 0');
    con.execute(insert, params, function(err) {
      if (err) { return console.log(err.message); }
      var insert = 'insert into test_binds (num, str, dt) values (:num, :str, :dt) returning num into :outNum';
      var params = {
        num: 123,
        str: 'str',
        dt: new Date(),
        outNum: { type: oracledb.NUMBER, dir: oracledb.BIND_OUT }
      };
      con.execute(insert, params, function(err) {
        if (err) { return console.log(err.message); }
        console.log('insert ok 0');
        con.execute('select * from test_binds', function(err, res) {
          if (err) { return console.log((err.message)); }
          console.log(res);
        });
      });
    });
  });
});
```

if remove dt field from insert query with returning, then work fine.

**Comment by cjbj** [comment] 2015-06-19 16:18
Thanks for the report.  We'll look into it.

**Comment by mynoheart** [comment] 2015-06-22 11:51
I found line when error hapen's.
src/njs/src/njsConnection.cpp:
```c
void Connection::PrepareAndBind (eBaton* executeBaton)
{
    executeBaton->dpistmt = executeBaton->dpiconn->getStmt(executeBaton->sql);
    executeBaton->st = executeBaton->dpistmt->stmtType ();
    executeBaton->stmtIsReturning = executeBaton->dpistmt->isReturning ();

    if(!executeBaton->binds.empty())
    {
      if(!executeBaton->binds[0]->key.empty())
      {
        for(unsigned int index = 0 ;index < executeBaton->binds.size();
            index++)
        {
          /* DML Returning does not support DATE/TIME database types
           * return error in that case
           */
-->          if ( executeBaton->stmtIsReturning &&
               (executeBaton->binds[index]->type == DpiTimestampLTZ ) )
          {

            executeBaton->error = NJSMessages::getErrorMsg (
                                              errInvalidBindDataType, 2);
            return;
          }
          
```

In comment written that DML Returning not support DATE/TIME.
This limitation also if DATE used as IN bind?

**Comment by mynoheart** [comment] 2015-06-22 11:56
If just comment this condition, then al work fine.

**Comment by cjbj** [comment] 2015-06-23 04:27
The limitation will only be for RETURNING INTO.  The developer (who fixed the code test over the weekend, BTW) reminded me I should document that limitation.  Thanks for the report & investigation. The fix will be in the next release to GitHub.

**Comment by mynoheart** [comment] 2015-06-23 06:35
Then this will be official behavior in case when in params used ```returning``` and date column even if it be as IN param?

**Comment by cjbj** [comment] 2015-06-23 14:50
Here's the output with the fix:

insert ok 0
insert ok 0
{ rows: 
   [ [ 123, 'str', Tue Jun 23 2015 07:50:11 GMT-0700 (PDT) ],
     [ 123, 'str', Tue Jun 23 2015 07:50:11 GMT-0700 (PDT) ] ],
  resultSet: undefined,
  outBinds: undefined,
  rowsAffected: undefined,
  metaData: [ { name: 'NUM' }, { name: 'STR' }, { name: 'DT' } ] }

**Comment by mynoheart** [comment] 2015-06-23 14:54
what fix you mean?

**Comment by cjbj** [comment] 2015-06-23 14:56
The fix that will be forthcoming.  See https://github.com/oracle/node-oracledb/issues/121#issuecomment-114350904

**Comment by mynoheart** [comment] 2015-06-23 14:58
Not use RETURNING?

**Comment by cjbj** [comment] 2015-06-23 15:06
@mynoheart What exact situation do you mean?

**Comment by mynoheart** [comment] 2015-06-23 15:13
@cjbj Situation, when need return result ```sequence.nextval``` after insert row where column contains DATE.

```js
var insert = 'insert into test_binds (id, dt) values (seq.nextval, :dt) returning id into :id_out';
var params = {
   dt: new Date(),
   id_out: {
     type: oracledb.NUMBER,
     dir: oracledb.BIND_OUT
   };
};
```

**Comment by cjbj** [comment] 2015-06-23 16:31
```javascript
var oracledb = require('oracledb');
var dbConfig = require('./dbconfig.js');

// drop sequence seq;
// create sequence seq;
// drop table test_binds;
// create table test_binds (id number, dt date);

// Side comment: with Oracle DB 12c, you can create an identity column and don't need an explicit sequence.

oracledb.getConnection(
  {
    user          : dbConfig.user,
    password      : dbConfig.password,
    connectString : dbConfig.connectString
  },
  function(err, con) {
    if (err) { return console.error(err.message); }
    var insert = 'insert into test_binds (id, dt) values (seq.nextval, :dt) returning id into :id_out';
    var params = {
      dt: new Date(),
      id_out: {
        type: oracledb.NUMBER,
        dir: oracledb.BIND_OUT
      }
    };
    con.execute(
      insert,
      params,
      function(err, result)
      {
        if (err) { return console.error(err.message); }
        console.log(result);
      });
  });
```

Output is

```
{ rowsAffected: 1,
  outBinds: { id_out: [ 1 ] },
  rows: undefined,
  metaData: undefined }
```

**Comment by mynoheart** [comment] 2015-06-23 17:59
My output is
```
NJS-012: encountered invalid bind datatype in parameter 2
```

**Comment by cjbj** [comment] 2015-06-23 18:30
You don't have the fix yet.

**Comment by mynoheart** [comment] 2015-06-23 18:57
Sorry, but i not understand last comment.

**Comment by cjbj** [comment] 2015-06-23 20:53
Apologies for brevity due to me preparing to travel.  The output I showed will be expected behavior in the next release. If you want something different, let us know.

**Comment by mynoheart** [comment] 2015-06-23 21:04
Thanks, now all became clear :-)

**Comment by mynoheart** [comment] 2015-07-22 14:06
Hello. In release 0.7.0 problem fixed, but DATE as out param not works. This technical limitiation?

**Comment by cjbj** [comment] 2015-07-23 01:59
@mynoheart thanks for confirming the fix.

Yes, RETURNING INTO currently only supports character & number bind types.  We have date support on the big 'todo' list.  But you can already return dates from PL/SQL binds.  This works in 0.7:
```javascript
var oracledb = require('oracledb');
var dbConfig = require('./dbconfig.js');

oracledb.getConnection(
  {
    user          : dbConfig.user,
    password      : dbConfig.password,
    connectString : dbConfig.connectString
  },
  function(err, connection)
  {
    if (err) {
      console.error(err.message);
      return;
    }
    connection.execute(
      "begin select sysdate into :d from dual; end;",
      {
        d : {dir:oracledb.BIND_OUT, type:oracledb.DATE }
      },
      function(err, result)
      {
        if (err) {
          console.error(err.message);
          return;
        }
        console.log(result);
      });
  });
```

**Closed by cjbj** 2015-07-23 01:59 UTC
Labels: bug

**Comment by mynoheart** [comment] 2015-07-23 06:27
Thanks.
