### ISSUE TITLE
Cannot install oracledb on node:latest

### ISSUE THREAD

**Issue by craigtmoore** [oracle/node-oracledb#902] opened 2018-04-30 20:27 UTC
I am unable to install the oracledb on the node:latest docker image:

This is what I see:

```
$ docker run -it --entrypoint /bin/bash node:latest 
root@76e5215c5097:/# npm install oracledb --save

> oracledb@2.2.0 install /node_modules/oracledb
> node package/oracledbinstall.js

oracledb Beginning installation
oracledb Verifying installation
oracledb Continuing installation
oracledb ERR! NJS-054: Binary build/Release/oracledb.node was not installed.
oracledb ERR! Pre-built binary packages are not available for this version of Node.js (NODE_MODULE_VERSION="64")
oracledb ERR! Failed to install binary package oracledb-v2.2.0-node-v64-linux-x64.gz
oracledb ERR! Error: HTTPS request for https://github.com/oracle/node-oracledb/releases/download/v2.2.0/oracledb-v2.2.0-node-v64-linux-x64.gz failed with code 404
oracledb ERR! For help see https://oracle.github.io/node-oracledb/INSTALL.html#troubleshooting

npm WARN enoent ENOENT: no such file or directory, open '/package.json'
npm WARN !invalid#1 No description
npm WARN !invalid#1 No repository field.
npm WARN !invalid#1 No README data
npm WARN !invalid#1 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 87
npm ERR! oracledb@2.2.0 install: `node package/oracledbinstall.js`
npm ERR! Exit status 87
npm ERR! 
npm ERR! Failed at the oracledb@2.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-04-30T20_17_06_809Z-debug.log
root@76e5215c5097:/# cat /root/.npm/_logs/2018-04-30T20_17_06_809Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'oracledb',
1 verbose cli   '--save' ]
2 info using npm@5.6.0
3 info using node@v10.0.0
4 verbose npm-session b17c3ab226b6b374
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/oracledb 106ms
8 silly pacote tag manifest for oracledb@latest fetched in 140ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule oracledb@2.2.0 checking installable status
14 silly currentTree !invalid#2
15 silly idealTree !invalid#1
15 silly idealTree `-- oracledb@2.2.0
16 silly install generateActionsToTake
17 silly diffTrees action count 1
18 silly diffTrees add oracledb@2.2.0
19 silly decomposeActions action count 8
20 silly decomposeActions fetch oracledb@2.2.0
21 silly decomposeActions extract oracledb@2.2.0
22 silly decomposeActions preinstall oracledb@2.2.0
23 silly decomposeActions build oracledb@2.2.0
24 silly decomposeActions install oracledb@2.2.0
25 silly decomposeActions postinstall oracledb@2.2.0
26 silly decomposeActions finalize oracledb@2.2.0
27 silly decomposeActions refresh-package-json oracledb@2.2.0
28 silly install executeActions
29 silly doSerial global-install 8
30 verbose correctMkdir /root/.npm/_locks correctMkdir not in flight; initializing
31 verbose makeDirectory /root/.npm/_locks creation not in flight; initializing
32 silly makeDirectory /root/.npm/_locks uid: 0 gid: 0
33 verbose lock using /root/.npm/_locks/staging-781faa38490e6896.lock for /node_modules/.staging
34 silly doParallel extract 8
35 silly extract oracledb@2.2.0
36 silly pacote trying oracledb@https://registry.npmjs.org/oracledb/-/oracledb-2.2.0.tgz by hash: sha512-ywwalyryeJYb5dr1JScyPcNxCeN0zExrKLtorSdptBZqhfS5Dp9KLgGOExc+XMMfEejXGtC/RfiDxKaGn6+VJA==
37 silly pacote data for sha512-ywwalyryeJYb5dr1JScyPcNxCeN0zExrKLtorSdptBZqhfS5Dp9KLgGOExc+XMMfEejXGtC/RfiDxKaGn6+VJA== not present. Using manifest.
38 http fetch GET 200 https://registry.npmjs.org/oracledb/-/oracledb-2.2.0.tgz 116ms
39 silly pacote oracledb@https://registry.npmjs.org/oracledb/-/oracledb-2.2.0.tgz extracted in 139ms
40 silly doReverseSerial unbuild 8
41 silly doSerial remove 8
42 silly doSerial move 8
43 silly doSerial finalize 8
44 silly finalize /node_modules/oracledb
45 silly doParallel refresh-package-json 8
46 silly refresh-package-json /node_modules/oracledb
47 silly doParallel preinstall 8
48 silly preinstall oracledb@2.2.0
49 info lifecycle oracledb@2.2.0~preinstall: oracledb@2.2.0
50 silly doSerial build 8
51 silly build oracledb@2.2.0
52 info linkStuff oracledb@2.2.0
53 silly linkStuff oracledb@2.2.0 has /node_modules as its parent node_modules
54 verbose linkBins oracledb@2.2.0
55 verbose linkMans oracledb@2.2.0
56 silly doSerial global-link 8
57 silly doParallel update-linked 8
58 silly doSerial install 8
59 silly install oracledb@2.2.0
60 info lifecycle oracledb@2.2.0~install: oracledb@2.2.0
61 verbose lifecycle oracledb@2.2.0~install: unsafe-perm in lifecycle false
62 verbose lifecycle oracledb@2.2.0~install: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/node_modules/oracledb/node_modules/.bin:/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
63 verbose lifecycle oracledb@2.2.0~install: CWD: /node_modules/oracledb
64 silly lifecycle oracledb@2.2.0~install: Args: [ '-c', 'node package/oracledbinstall.js' ]
65 silly lifecycle oracledb@2.2.0~install: Returned: code: 87  signal: null
66 info lifecycle oracledb@2.2.0~install: Failed to exec install script
67 verbose unlock done using /root/.npm/_locks/staging-781faa38490e6896.lock for /node_modules/.staging
68 silly saveTree !invalid#1
68 silly saveTree `-- oracledb@2.2.0
69 warn enoent ENOENT: no such file or directory, open '/package.json'
70 verbose enoent This is related to npm not being able to find a file.
71 warn !invalid#1 No description
72 warn !invalid#1 No repository field.
73 warn !invalid#1 No README data
74 warn !invalid#1 No license field.
75 verbose stack Error: oracledb@2.2.0 install: `node package/oracledbinstall.js`
75 verbose stack Exit status 87
75 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
75 verbose stack     at EventEmitter.emit (events.js:182:13)
75 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
75 verbose stack     at ChildProcess.emit (events.js:182:13)
75 verbose stack     at maybeClose (internal/child_process.js:947:16)
75 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:236:5)
76 verbose pkgid oracledb@2.2.0
77 verbose cwd /
78 verbose Linux 4.13.0-39-generic
79 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "oracledb" "--save"
80 verbose node v10.0.0
81 verbose npm  v5.6.0
82 error code ELIFECYCLE
83 error errno 87
84 error oracledb@2.2.0 install: `node package/oracledbinstall.js`
84 error Exit status 87
85 error Failed at the oracledb@2.2.0 install script.
85 error This is probably not a problem with npm. There is likely additional logging output above.
86 verbose exit [ 87, true ]
```

#### Answer the following questions:

1. What is your Node.js version?  Is it 64-bit or 32-bit?  Run `version.js` from https://github.com/oracle/node-oracledb/blob/master/examples/version.js

```
root@76e5215c5097:/# nodejs --version
v10.0.0
```

2. What is your node-oracledb version?

> Failed to install binary package oracledb-v2.2.0-node-v64-linux-x64.gz

3. What is your OS and version?

```
root@76e5215c5097:/# uname --all
Linux 76e5215c5097 4.13.0-39-generic #44~16.04.1-Ubuntu SMP Thu Apr 5 16:43:10 UTC 2018 x86_64 GNU/Linux
root@76e5215c5097:/# cat /etc/issue
Debian GNU/Linux 8 \n \l
```

4. What is your compiler version?  For example, with GCC, run `gcc --version`

```
root@76e5215c5097:/# gcc --version
gcc (Debian 4.9.2-10+deb8u1) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

5. What Oracle environment variables did you set?  How *exactly* did you set them?

None

6. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?

```
root@76e5215c5097:/# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
root@76e5215c5097:/# echo $LD_LIBRARY_PATH
''
```

7. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?

See above. Docker runs as root

8. What error(s) you are seeing?

I think the problem is that its trying to download:

oracledb-v2.2.0-node-v64-linux-x64.gz

but it should be should be:

oracledb-v2.2.0-node-**_v46_**-linux-x64.gz

Based on the release file names under: 
https://github.com/oracle/node-oracledb/releases/tag/v2.2.0

**Comment by cjbj** [comment] 2018-04-30 22:00
Duplicate of #901 :)

**Closed by cjbj** 2018-04-30 22:00 UTC
