### ISSUE TITLE
General: connection release woes

### ISSUE THREAD

**Issue by DavidWhit** [oracle/node-oracledb#520] opened 2016-10-05 21:39 UTC
*Delete irrelevant parts of this template.*

The pool overflows and I'm not queuing any additional requests to wait if it hits the max. I just wanted to start simple and work from there. I've determined the connections are not being release after logging pool stats when they should be released and feel I have been stuck looking at the same stuff and was hoping for some guidance. I looked over the docs and googled some. Hoping someone can shed some light on it; still newbie.

Criticism welcomed

```
function queryData(sql, bindVars={}) {
    let data = []
    const executeParams = {
        outFormat: oracledb.OBJECT,
        resultSet: true
    }
    const fetchSize = 1000

    function getData(connection, resultSet, fetchSize, data) {
      resultSet.getRows(fetchSize)
        .then( rows => {
            if (rows.length === fetchSize) {
                data.push(...rows)
                getData(connection, resultSet, fetchSize, data)
            }
            else if (rows.length > 0 ){
                data.push(...rows)
                resultSet.close()
                connection.close()
                Promise.resolve(data)
            }
            else {
                resultSet.close()
                connection.close()
                Promise.resolve(data)
            }
        })
        .catch(err => Promise.reject(err))
    }
    
    return oracledb.getConnection('dash')
            .then( connection => {
              connection.execute(sql, bindVars, executeParams)
                .then( result => getData(connection, result.resultSet, fetchSize,data))
                .catch( err => {
                  Promise.reject(err)
                  process.nextTick( () => connection.release() )
                })
            })
            .catch( err =>  Promise.reject(err) )
}
```

and somewhere else I poll for initial data like 

```
  function init(pool) {
    Promise.all( Object.keys(queries).map( i =>
      database.queryData(queries[i].sql, {}))
    )
    .then( results => {
      cachedData.data = results
      cachedData.time = moment()
      console.log(`Data refreshed@ ${cachedData.time}`)
    })
    .then(() => pool._logStats())
    .catch( err => console.log(err))
  }
```

**Comment by dmcghan** [comment] 2016-10-05 22:10
@DavidWhit You only seem to release the connection in the `catch` block, but you should release in the `then` too.

Also, in `queryData `, you're returning the promise from `getConnection`, but that resolves as soon as the connection is obtained. Consider creating and returning a new Promise that you resolve or reject accordingly (when the connection is released either way).

**Comment by DavidWhit** [comment] 2016-10-05 23:37
@dmcghan Hi Dan, I have written it a few ways and that was the last iteration I came to. Previously  I did wrap the whole thing in a new Promise like you suggested like this.

```
function queryData(sql, bindVars={}) {
    let data = []
    const executeParams = {
        outFormat: oracledb.OBJECT,
        resultSet: true
    }
    const fetchSize = 1000

    return new Promise( (resolve,reject) => {

      function getData(connection, resultSet, fetchSize, data) {
        resultSet.getRows(fetchSize)
          .then( rows => {
              if (rows.length === fetchSize) {
                  data.push(...rows)
                  getData(connection, resultSet, fetchSize, data)
              }
              else if (rows.length > 0 ){
                  data.push(...rows)
                  resultSet.close()
                  connection.close()
                  resolve(data)
              }
              else {
                  resultSet.close()
                  connection.close()
                  resolve(data)
              }
          })
          .catch(err => reject(err))
      }

       oracledb.getConnection('dash')
              .then( connection => {
                connection.execute(sql, bindVars, executeParams)
                  .then( result => {
                    process.nextTick( () => connection.release())
                    return getData(connection, result.resultSet, fetchSize,data)   
                  })
                  .catch( err => {
                    reject(err)
                    process.nextTick( () => connection.release() )
                  })
              })
              .catch( err =>  reject(err) )
      })
  }
```
I originally thought to pass along the connection to close it after I got all the result sets like the oracledb docs suggest, but it doesn't appear to close it there either ( i just left the code in). 
And in the then I have also tried it there as well in different order for the sake of trying..

In this case the return does look more clean but the results are the same; perhaps I missed it. And because I'm new and there is contradiction. I wanted to bring up the return queryData wouldn't resolve at the getConnection being there are more thenables. [(https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/resolve)]  Not trying to argue just it's confusing when I'm learning.

Thanks for your time, Dave

**Comment by dmcghan** [comment] 2016-10-05 23:54
@DavidWhit This process would likely go faster if you wrote a reproducible test case I could use on my side. I'll entertain this a little longer without one. :)

Are you getting an error?

Now it looks like we are closing the connection in the `then` of `connection.execute` AND `getData`. Which do you want to use? If `getData`, remove the other close and move your `connection.close` calls into the callbacks of the `resultSet.close` calls as you need to be sure the resultSets are closed before closing the connection. I recommend resolving in the callback of `connection.close`.

**Comment by DavidWhit** [comment] 2016-10-06 14:28
No errors, other than the pool timeout; however,

 "Now it looks like we are closing the connection in the then of connection.execute AND getData" I mentioned that I just left it in. My intention was to point out I've tried both places. 

You guys are great at supporting this to the community. It came to your statement of the close callbacks. I didn't realize the close where promises and assumed it would be done at the time of call. So

```
...
   {  
      data.push(...rows)
      return resultSet.close()
                    .then( () =>
                      connection.close()
                        .then( () =>
                        resolve(data))
                    )
  }

```

I'll try and clean things up by flattening the chains just to practice.

Thanks, Dave

**Closed** 2016-10-06 14:35 UTC

**Comment by dmcghan** [comment] 2016-10-06 14:56
That looks much better. It's a little worrisome, however, that you weren't getting any error messages. My guess is that an error was being thrown but there was no handler for it as you weren't expecting a promise. There's a [note in the doc](https://github.com/oracle/node-oracledb/blob/master/doc/api.md#-19-promises-in-node-oracledb) on Promises that mentions adding a handler for the `unhandledRejection` event. I highly recommend doing this if you're going to work with Promises.

So you know, just about every method is async. If an async method is not passed a callback it returns a Promise. The only methods that are currently synchronous are:

- `oracledb.getPool`
- `resultset.toQueryStream`
- `connection.queryStream`

We hope to improve the doc and make this more obvious in the future.

**Comment by DavidWhit** [comment] 2016-10-06 15:00
Thanks for those points I will definitely polish it. I think the docs are great just have to reread it till they sink in. When I looked back it did show Promise was returned by the close so I clearly over looked it, but I spent such a great deal of time trenching through them.

**Comment by sagiegurari** [comment] 2016-10-06 15:06
if you are using pools and not creating a connection every time, you could look at pool.run which does the get connection for you and the release connection as well.
this way you don't have to ensure that all cases are covered and that you release the connection in every scenario.

https://github.com/sagiegurari/simple-oracledb#usage-pool-run

for example:

````js
pool.run(function (connection, callback) {
  //run some query and the output will be available in the promise then callback
  connection.query('SELECT department_id, department_name FROM departments WHERE manager_id < :id', [110], callback);
}).then(function (queryData) {
  //do something...
});
````

**Comment by DavidWhit** [comment] 2016-10-06 15:14
I have looked at your library and it's great work. It does make things more simple hence the name :). I just wanted to understand the flow and handle of things in the underlying dependency before using a library. I did the same with d3 before switching to a library that implemented it.
