### ISSUE TITLE
Error connecting when I used Bun 

### ISSUE THREAD

**Issue by willikornelius** [oracle/node-oracledb#1699] opened 2024-10-20 05:46 UTC
1. What versions are you using?

```
6.6.0 version oracledb
19.9/21.15/23.05 version oracle client
1.1.22 version Bun
```

2. Is it an error or a hang or a crash?
```
638 |     _initializeThinDriver();
639 |   }
640 |
641 |   const conn = new Connection();
642 |   conn._impl = new impl.ConnectionImpl();
643 |   await conn._impl.connect(options);

error: internal error in file D:\git_files\node-oracledb\src\njsUtils.c, line 805 ()
 code: "internal error in file D"
```

When i used nodejs, its running,. 
Problem : when i used bun  
                         

3. What error(s) or behavior you are seeing?
```
638 |     _initializeThinDriver();
639 |   }
640 |
641 |   const conn = new Connection();
642 |   conn._impl = new impl.ConnectionImpl();
643 |   await conn._impl.connect(options);

error: internal error in file D:\git_files\node-oracledb\src\njsUtils.c, line 805 ()
 code: "internal error in file D"
```

4. Include a runnable Node.js script that shows the problem.

**Comment by cjbj** [comment] 2024-10-20 10:39
Can you share a runnable Node.js script that shows the problem?

**Comment by willikornelius** [comment] 2024-10-20 10:53
```
try {
    oracledb.initOracleClient({ libDir: Bun.env.DB_ORACLE_ORACLIENT_LOCAL });
  } catch (err) {
    console.error('Error Connection');
    console.error(err);
    process.exit(1);
  }
  try {
    connection = await oracledb.getConnection({
      user: Bun.env.DB_ORACLE_USER_O,
      password: Bun.env.DB_ORACLE_PASSWORD_0,
      connectString: Bun.env.DB_ORACLE_CONNECTSTRING_O,
    });
    console.log(' step 1');
    let sql = `BEGIN ${procName} (XMLType(:IN),:cursor); END;`;

    result = await connection.execute(
      sql,
      {
        IN: dt,
        cursor: { type: oracledb.CURSOR, dir: oracledb.BIND_OUT },
      },
      // { outFormat: oracledb. },
    );

    cursor = result.outBinds.cursor;
    const queryStream = cursor.toQueryStream();
    const consumeStream = new Promise((resolve, reject) => {
      queryStream.on('data', function (row: any) {
        pushData = [...pushData, row];
      });
      queryStream.on('error', reject);
      queryStream.on('close', resolve);
    });

    await consumeStream;
  } catch (err: unknown) {
    console.error('masuk error ', err);
  } finally {
    if (connection) {
      try {
        await connection.close();
        //console.log('Request In (Close Connection) - getwarehouse');
      } catch (err: unknown) {
        console.error(err);
      }
    }
  }
```


I couldnt reach log : step 1 sir @cjbj 
the issue is similar to https://github.com/oven-sh/bun/issues/11851

**Comment by sharadraju** [comment] 2024-11-05 04:30
Closing this as this is a duplicate of Issue #1699

**Closed by sharadraju** 2024-11-05 04:30 UTC
Labels: bug, duplicate
