### ISSUE TITLE
NJS-069: node-oracledb 6.0.3 requires Node.js 14.6 or later. 

### ISSUE THREAD

**Issue by labkapapka** [oracle/node-oracledb#1596] opened 2023-08-23 09:47 UTC
Hi!
I have problem with  node-oracledb.
When I launch my test-case in Cypress - I get error: NJS-069: node-oracledb 6.0.3 requires Node.js 14.6 or later. 
But my current version:
oracledb@6.0.3
Node JS version v18.16.0

Cypress package version: 12.17.4
Cypress binary version: 12.17.4
Electron version: 21.0.0
Bundled Node version:
16.16.0
Could you help me solve the problem?

1. What versions are you using?

2. Is it an error or a hang or a crash?

3. What error(s) or behavior you are seeing?

4. Include a runnable Node.js script that shows the problem.

**Comment by sharadraju** [comment] 2023-08-23 11:28
Hi,
Please provide a running test case, that describes the problem

**Comment by sudarshan12s** [comment] 2023-08-23 12:06
@labkapapka , It looks like the process which ran the test case used older node.js version ? Can you confirm if there are multiple node.js versions on your host and somehow Cypress tests points to older versions (<14.6) ..  You can verify once by calling  `console.log(process.versions.node)` from  Cypress tests before loading `oracledb` module ?   Can you also share the output of `node example/version.js .` We use `process.version` to detect the node version .

**Comment by labkapapka** [comment] 2023-08-23 12:51
> @labkapapka , It looks like the process which ran the test case used older node.js version ? Can you confirm if there are multiple node.js versions on your host and somehow Cypress tests points to older versions (<14.6) .. You can verify once by calling `console.log(process.versions.node)` from Cypress tests before loading `oracledb` module ? Can you also share the output of `node example/version.js .` We use `process.version` to detect the node version .

Hm, i get 'undefined' when try calling console.log(process.versions.node).
The output of `node example/version.js is Node.js v18.16.0

**Comment by sudarshan12s** [comment] 2023-08-23 13:47
> > @labkapapka , It looks like the process which ran the test case used older node.js version ? Can you confirm if there are multiple node.js versions on your host and somehow Cypress tests points to older versions (<14.6) .. You can verify once by calling `console.log(process.versions.node)` from Cypress tests before loading `oracledb` module ? Can you also share the output of `node example/version.js .` We use `process.version` to detect the node version .
> 
> Hm, i get 'undefined' when try calling console.log(process.versions.node) from Cypress test before loading oracledb module. The output of `node example/version.js is Node.js v18.16.0

You have imported process in the file like below , where you have called?  It is part of node.js [process](https://nodejs.org/api/process.html#processversions) module 
`const process = require('process');`

**Comment by labkapapka** [comment] 2023-08-23 14:23
> Yes, but result the same.

Yes, but result the same.

**Comment by sudarshan12s** [comment] 2023-08-23 14:23
Can you try `console.log(process.version);` which we used inside driver (lib/oracledb.js)  . It looks like inside Cypress tests,  the same property `process.version` got overwritten as standalone (examples/version.js) works fine ?  Can you cross check ?. Does an explicit `const process = `require('node:process'); ``help  ?

**Comment by labkapapka** [comment] 2023-08-23 14:26
I'm no shure that a can.
I just start to write tests on JS + Cypress.
Which code and where i should run?

**Comment by labkapapka** [comment] 2023-08-23 14:49
> Can you try `console.log(process.version);` which we used inside driver (lib/oracledb.js) . It looks like inside Cypress tests, the same property `process.version` got overwritten as standalone (examples/version.js) works fine ? Can you cross check ?. Does an explicit `const process = `require('node:process'); ``help ?

//oracledb.js
'use strict';

const constants = require('./constants.js');
const nodbUtil = require('./util.js');
const errors = require('./errors.js');
const types = require('./types.js');
const impl = require('./impl');
const process = require('process');
const util = require('util');

**Comment by sudarshan12s** [comment] 2023-08-23 14:54
I mean inside the Cypress test files, can you add this piece of code and let me know the result. 
```
{
      const process = require('node:process');
    console.log(process.version);
    }
```

**Comment by labkapapka** [comment] 2023-08-23 14:57
> I mean inside the Cypress test files, can you add this piece of code and let me know the result.
> 
> ```
>    {
>       const process = require('node:process');
>     console.log(process.version);
>     }
> ```

if i add this piece of code i get:
![image](https://github.com/oracle/node-oracledb/assets/133049829/ea972bcd-92ac-4086-b089-d5e765206a24)

**Comment by labkapapka** [comment] 2023-08-23 14:59
//test.cy.js
describe('TOKINIZER 3DS', () => {
const process = require('node:process');
   console.log(process.version);
    // const process = require('process');
    // console.log(process.versions.node);
    it('Ord.1, Tokinizer, LOOK UP, MC,', () => {
    const process = require('process');
    console.log(process.versions.node);
    const oracledb = require('oracledb');

oracledb.outFormat = oracledb.OUT_FORMAT_OBJECT;

async function run() {

    const connection = await oracledb.getConnection ({
        user          : "admin",
        password      : "admin!",
        connectString : "b0t.test.local:1521/tzw1pgttest.local"
    });

    const result = await connection.execute(
        `SELECT *
         FROM PTEMPDATA`,
          // bind value for :id
    );

    console.log(result.rows);
    await connection.close();
}

run();
    });
});

**Comment by sudarshan12s** [comment] 2023-08-23 17:43
I see your Cypress environment cant access node modules as it is .  Your tests passed with previous versions like oracledb@5.5?

**Comment by cjbj** [comment] 2023-08-23 23:06
Personally I suggest you hack our driver code in lib/oracledb.js where we throw the version check error and do either or both of:
- log the value of `process.version`.
- remove the version check and see if the driver works.

PS Please use triple backquotes to mark your code blocks in GitHub issues.

**Comment by labkapapka** [comment] 2023-08-24 06:58
> I see your Cypress environment cant access node modules as it is . Your tests passed with previous versions like oracledb@5.5?

No, tests wasn't success when I use oracledb@5.5.
I get the same Error, like this: "node-oracledb 5.x.x requires Node.js 8.x or later"

**Comment by labkapapka** [comment] 2023-08-24 07:01
> 

Give me, please, extended guide how to do this.
Which code and where I need to write?

**Comment by sharadraju** [comment] 2023-08-24 12:45
@labkapapka You might want to try what this user did to enable cypress to work with node-oracledb:
[https://github.com/oracle/node-oracledb/issues/1261#issuecomment-777880518](https://github.com/oracle/node-oracledb/issues/1261#issuecomment-777880518)

Based on the inputs from this issue, it seems cypress does not have a node version available in its spec files, so even trying to import/require oracledb causes immediate failure with the NJS-069 errror

**Comment by sharadraju** [comment] 2023-08-25 11:24
This is a duplicate of #1261. Hence closing this issue.
Request the user to refer to issue #1261

**Closed by sharadraju** 2023-08-25 11:24 UTC
Labels: duplicate, install & configuration
