### ISSUE TITLE
Oracledb is built every time I execute npm install no matter what package

### ISSUE THREAD

**Issue by MickelSierra85** [oracle/node-oracledb#431] opened 2016-05-18 07:27 UTC
Hi,
I can't understand why node-gyp is rebuilding oracledb module even if I execute:
'npm install gulp' command.

Any clues?

**Comment by cjbj** [comment] 2016-05-18 12:10
Knowing some details would help us.

**Comment by MickelSierra85** [comment] 2016-05-23 07:09
Hi, 
Thanks for the response.

steps to reproduce:
1. open a new folder and run express tool
2. npm install express dependencies
3. npm install oracledb
4. npm install express-ntlm

at step 4 please notice that node-gyp is rebuilding oracledb. 
The relevant lines for the output:

"if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch."

Why is node-gyp rebuilding oracledb?

Thanks.

**Comment by MickelSierra85** [comment] 2016-06-09 07:43
Hi,
@cjbj any ideas?

Thanks.

**Comment by cjbj** [comment] 2016-06-09 08:04
Nope.

**Comment by cjbj** [comment] 2016-06-14 01:40
@MickelSierra85 did you dig into this any further and check why not having oracledb in your package.json is causing this?

**Comment by cjbj** [comment] 2016-07-21 02:28
@MickelSierra85 ping.  Did you track down the cause?

**Comment by cjbj** [comment] 2016-07-27 01:52
Closing - no feedback

**Closed by cjbj** 2016-07-27 01:52 UTC
Labels: Install & Configuration
