### ISSUE TITLE
Writing unicode characters to CLOB stream gives unexpected string growth

### ISSUE THREAD

**Issue by wallride** [oracle/node-oracledb#1069] opened 2019-03-18 18:37 UTC
Hi again! :) I've got another problem while trying to play with LOBs.
It's a problem with unicode characters (tat take more then 1 byte to store). When I write such a character to a CLOB an additional space character (or may be just 0x00 byte) appears after the written chunk. The more special symbols, the more spaces I see...
Google and experiments with specifying 'utf8' encoding gave nothing...

Here's a code example to reproduce the problem:
```
const oracle = require('oracledb');

// PL/SQL Procedure
// CREATE PROCEDURE mock_lob(P_CLOB IN OUT CLOB) AS BEGIN NULL; END;

const originString = 'dddЩЩЩ';

oracle.getConnection({connectString:'odb_app', user: 'system', password: 'oracle'}, (err, connection) => {
    connection.createLob(oracle.CLOB, (err, clob) => {
        if (err) {
            console.error(err);
            return;
        }

        console.log('CLOB created');

        // Write originString to clob many times

        let sentData = '';

        for (let i = 0; i < 1000; i++) {
            clob.write(originString);
            sentData += originString;
        }
        clob.end();

        clob.on('finish', async () => {
            console.log('Write to CLOB complete');
            let outClob;

            // Now execute: pass the populated clob to procedure and receive another clob that is expected to equal origin one

            try {
                const result = await connection.execute(
                    'begin mock_lob(P_CLOB => :clob); end;',
                    {clob: {type: oracle.CLOB, dir: oracle.BIND_INOUT, val: clob}},
                    {outFormat: oracle.OBJECT}
                );
                outClob = result.outBinds['clob'];
            } catch(e) {
                console.error(e);
                return;
            }
            finally {
                clob.close();
            }

            // Read the received clob object an check data consistency

            let receivedData = '';
            outClob.on('data', chunk => {
                const slice = sentData.slice(receivedData.length, receivedData.length + chunk.length);

                if (slice !== chunk)
                    throw new Error(`Unequal part ${receivedData.length}-${receivedData.length + chunk.length}\n${slice}\n${chunk}`);

                receivedData += chunk;
            })
        });
    });
});

```

Can anyone explain what am I missing?

**Comment by anthony-tuininga** [comment] 2019-03-18 20:04
I have replicated the issue and have a patch that corrects it available. @cjbj will push it out to the dev-4.0 branch once it has been tested further internally.

**Comment by cjbj** [comment] 2019-03-21 05:33
@wallride I pushed [the proposed patch](https://github.com/oracle/node-oracledb/commit/058c2fabe882aa0b81e612a999f6c5edd0c7cb7d) to the dev-4.0 branch.  Tests are still pending, but please let us know what you find.  See https://github.com/oracle/node-oracledb/issues/1053#issuecomment-472233930 for info about installing this development branch.

**Comment by wallride** [comment] 2019-06-27 16:02
@cjbj I switched to dev-4.0 and got another error (not related with this particular issue). Probably you are aware of it.

Statement:
```
begin "TEST".createItem(
    P_CODE =>     :code,
    P_CREATED =>  :created,
    P_BIN =>      :bin,
    P_ID =>       :id
); end;
```

Bind parameters:
```
 { code: { type: 2001, dir: 3002, val: 'code-0' },
  created: { type: 2014, dir: 3001, val: new Date() },
  bin: { type: 2006, dir: 3001, val: <Buffer 30> },
  id: { type: 2010, dir: 3003 } } { outFormat: 4002, fetchInfo: {} }
```
Got an error: `Error: NJS-012: encountered invalid bind data type in parameter 2`.

So, I cannot test the patch. :)

**Comment by anthony-tuininga** [comment] 2019-06-27 18:49
Can you provide the full code that you are using? Without that it is very hard to know why you might be getting that error.

**Comment by cjbj** [comment] 2019-06-28 00:37
@wallride our regressions are passing, so we don't know about it.  Please tell us more, as @anthony-tuininga recommended.

**Comment by cjbj** [comment] 2019-06-30 22:09
@wallride I couldn't reproduce any problem with [issue1069.js](https://gist.github.com/cjbj/93d4b33d5479b01a991c9a73fe5ed44d#file-issue1069-js)

**Comment by cjbj** [comment] 2019-07-17 05:14
@wallride ping?

**Comment by cjbj** [comment] 2019-07-25 06:18
@wallride Node-oracledb 4.0 has been released with a fix for the original problem. We couldn't reproduce your later report.  The release announcement is at https://blogs.oracle.com/opal/oracle-db-named-objects-and-advanced-queuing-support-new-in-node-oracledb-40

**Closed by cjbj** 2019-07-25 06:18 UTC
Labels: bug
