### ISSUE TITLE
BLOB Support

### ISSUE THREAD

**Issue by kumarmugu** [oracle/node-oracledb#101] opened 2015-05-21 08:09 UTC
Hi @cjbj and all,

I am using v0.4.1 for my NodeJS application. I want to save the image files in the oracle database.
Is this driver currently supporting to store/retrieve images (BLOB) ?

If can you please share the samples/Help.
Thanks for the help and support

K.Mugunthan

**Comment by cjbj** [comment] 2015-05-21 15:35
@kumarmugu LOB support is being worked on.  I'll close this as a duplicate of https://github.com/oracle/node-oracledb/issues/19

**Closed by cjbj** 2015-05-21 15:35 UTC

**Comment by hola5456** [comment] 2015-06-13 12:12
hello @cjbj ,
i need LOB Support please 
Thanks
