### ISSUE TITLE
Unable to resolve some modules in Meteor 1.4.1.1

### ISSUE THREAD

**Issue by oursonvie** [oracle/node-oracledb#516] opened 2016-09-26 01:25 UTC
I installed oracledb using 

```
meteor npm install --save meteor-node-stubs
meteor npm install oracledb --save
```

then when I try to load the module it turns me

```
Unable to resolve some modules:

  "../build/Release/oracledb" in
/Users/Tonny/Desktop/oracle/myapp/node_modules/oracledb/lib/oracledb.js
(web.browser)
  "../build/Debug/oracledb" in
/Users/Tonny/Desktop/oracle/myapp/node_modules/oracledb/lib/oracledb.js
(web.browser)
```

I can run example code using node

in using Node v6.5.0, instantclient-basic-macos.x64-12.1.0.2.0, instantclient-sdk-macos.x64-12.1.0.2.0, oracledb 1.11.0 on macOS Sierra 10.12

**Comment by alberh** [comment] 2016-10-13 15:35
The same here, using Node 1.4.1.2 and an existing project. I've tried to re-build the package but didn't work.

Any hints?

**Comment by dmcghan** [comment] 2016-10-14 14:00
Have you reached out to the Meteor team? I'm wondering if there's a way to enable a more verbose error output. "Unable to resolve some modules" is not ver helpful...

**Comment by oursonvie** [comment] 2016-10-17 07:37
sorry guys, I did the Oracle part in Python while waiting for a valid solution

**Comment by cjbj** [comment] 2016-10-19 00:42
The first place to look with these kind of issues is whether the invoking shell has LD_LIBRARY_PATH set correctly.  If that's too complex to identify (sudo may clobber the environment, other shells may start with a clean env etc), and you only have the one Oracle client installed on the machine, look at using ldconfig on Linux.

**Comment by cjbj** [comment] 2016-12-08 00:32
Closing due to lack of progress.  I would like to know what the status is.  I wonder if its similar to #501 or #534

**Closed by cjbj** 2016-12-08 00:32 UTC
Labels: Install & Configuration

**Comment by dmcghan** [comment] 2016-12-16 00:00
@oursonvie @alberh I'm trying to reproduce the issue you ran into but I'm not having any luck. Here's an overview of what I did:

Installed Meteor:
```bash
curl https://install.meteor.com/ | sh
```

Installed the sample app and tested:
```bash
meteor create simple-todos
cd simple-todos                             
meteor npm install
meteor
```

That all worked fine. I stopped the application and then installed oracledb (meteor-node-stubs was already installed):
```bash
meteor npm install oracledb --save
```

Next, I modified server/main.js to import and use the driver (just a connection test):
```javascript
import { Meteor } from 'meteor/meteor';
import oracledb from 'oracledb';

oracledb.getConnection({
        user: "hr",
        password: "topsecret",
        connectString: "test-db/orcl"
    }).then(conn => {
       console.log('got conenction', conn);
    }).catch(err => {
       console.log('got error', err);
    });

Meteor.startup(() => {
  // code to run on server at startup
}); 
```

When I started the application again it started fine and connection details were logged to the terminal.

I'm unable to reproduce the error you're seeing. Could either of you create a reproducible test case?

**Comment by oursonvie** [comment] 2016-12-19 01:34
@dmcghan Thanks mate, I tried last week and I can confirm that the error is gone, at least for my case.

**Comment by cjbj** [comment] 2016-12-19 02:11
@oursonvie thanks for the confirmation. And thanks @dmcghan for chasing it up.
