### ISSUE TITLE
 Blocking on getConnection

### ISSUE THREAD

**Issue by syahiaoui** [oracle/node-oracledb#725] opened 2017-06-30 13:02 UTC
*Delete irrelevant parts of this template.*

### Questions:

My node application remains blocked when calling getConnection, We put traces and the call of the getconnection method never return a result.
I have no error on the application, on the browser the message appears "server does not respond " after a few minutes.

#### Answer's for questions:

1. Node version => 6.10.3
2. Node-oracledb version => 1.13.1

3. What is the version of your Oracle client (e.g. Instant Client)?  
oracleClientVersion":1201000200.
cd /opt/oracle
unzip instantclient-basic-linux.x64-12.2.0.1.0.zip
unzip instantclient-sdk-linux.x64-12.2.0.1.0.zip
mv instantclient_12_2 instantclient
cd instantclient
ln -s libclntsh.so.12.1 libclntsh.so

export LD_LIBRARY_PATH=/opt/oracle/instantclient:$LD_LIBRARY_PATH

4. Version of Oracle Database: 10g

5. What is your OS and version: 

Red Hat Enterprise Linux Server release 6.9 (Santiago)
Kernel \r on an \m

6.  gcc --version : 
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18)

7. My code:
a. create Pool:
```
function createPool() {
    oracledb.createPool({
            "_enableStats": true,
            "user": config.database.user,
            "password": config.database.password,
            "connectString": config.database.connectString,
            "poolMin": 5,
            "poolMax": 20,
            "poolTimeout": 60,
            "queueRequests": false,
            "queueTimeout": 1000
        },
        function(err, p) {
            if (err) {
                logger.error("can't create pool from oracle");
            } else {
                pool = p;
                logger.info(p); // default
            }
        });
}

module.exports.createPool = createPool;

function getPool() {
    if (pool != null) {
        return pool;
    }
    createPool();
    return;
}

module.exports.getPool = getPool;


function closePool() {
    if (pool != null) {
        pool.close();
    }
    pool = null;
    createPool();
}

module.exports.closePool = closePool;
```

b. getConnection and execute Query:
```
execute: (sql, binds, options, cb) => {
        var pool = db.getPool();
        if (typeof pool === 'undefined' || pool === null) {
            logger.error("Pool connection is undefined or null");
        } else {
            pool.getConnection((err, connection) => {
                if (err) {
                    logger.error(err.message);
                    db.closePool();
                    cb(err, null)
                    return;
                }
                connection.execute(sql, binds, options, (err, result) => {
                    // Release the connection
                    connection.release(
                        function(err) {
                            if (err) {
                                logger.error(err.message);
                            } else {
                                logger.info("Connection released");
                            }
                        });
                    cb(err, result);
                })
            });
        }
    }
```
8. I start my application with pm2

**Comment by cjbj** [comment] 2017-06-30 21:29
> "poolMax": 20,

Perhaps https://github.com/oracle/node-oracledb/blob/node-oracledb-v1/doc/api.md#numberofthreads ?

**Comment by cjbj** [comment] 2017-06-30 21:45
Another thing I noticed:

> oracleClientVersion":1201000200.
> cd /opt/oracle
> unzip instantclient-basic-linux.x64-12.2.0.1.0.zip

Those two version numbers are different.  Are you actually using the version of Oracle Instant client that you want? Maybe you have Instant Client 12.1 RPMs installed, and RPATH is being used? See https://github.com/oracle/node-oracledb/blob/node-oracledb-v1/INSTALL.md#linuxadv

**Comment by glipka** [comment] 2017-07-03 12:40
Hi 
UV_THREADPOOL_SIZE i set to 10 
When we replace call back by promise, the getConnection is no more blocked and th message "ORA-03113: end-of-file on communication channel\nProcess ID" is returned.  
Is it possible to set ENABLE=BROKEN  on the node server where the application is installed  ?  (no tnsnames.ora)
Best Regards

**Comment by cjbj** [comment] 2017-07-03 22:49
@glipka are you and @syahiaoui working at the same site?  If so, you have

> "poolMax": 20,

and

> UV_THREADPOOL_SIZE i set to 10

But the [doc I linked to before](https://github.com/oracle/node-oracledb/blob/node-oracledb-v1/doc/api.md#numberofthreads) says 

> The thread pool size should be at least equal to the maxiumum number of connections.

Try a `UV_THREADPOOL_SIZE` of 20 or more. And make sure it is set before Node.js threads are created.

Regarding tnsnames.ora settings, if you don't/can't have a tnsnames.ora file with the Node application, you could always hardcode the complete TNS connect string in the application.  From the [doc](https://github.com/oracle/node-oracledb/blob/master/doc/api.md#tnsnames):

> Full connection strings can be embedded in applications:
>```
> var oracledb = require('oracledb');
>
> oracledb.getConnection(
> {
>    user          : "hr",
>    password      : "welcome",
>    connectString : "(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=mymachine.example.com)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=orcl)))"
>  },
>  . . .
>```

**Comment by glipka** [comment] 2017-07-04 11:54
HI 

the version : 1202000100
UV_THREADPOOL_SIZE has been set to 20 
ENABLE=BROKEN has bean coded in the connexion string  
poolPingInterval = 0  
All connections are released after usage  (we verified source code and result of logstats) 

And we still have : ORA-03113 
how can we solve this problem ? 

Best Regards

**Comment by cjbj** [comment] 2017-07-05 02:22
Are you using a connection pool?

Re the version

> the version : 1202000100

Is this the client version or the DB version?

> poolPingInterval = 0

This value is not needed or used if you have a 12.2 client.

What does

> after a period of inactivity

really mean? How long?  What has the app done up to this point?  What does the app do afterwards?

What does

> when we try again

mean? Do you restart the app?  

Is this your scenario?:
- The app has done a getConnection().  
- The network drops out some. 
- The app uses the connection and gets ORA-3113.  
- The app releases the invalid connection. 
- The app does another getConnection()
- The app is able to use the connection.

If this is your scenario, then it is what I'd expect.  You should work out what is killing your connections (firewall, DB resource limit, DBA scripting killing idle sessions etc) and stop it.  You can check Oracle server and client trace files which might give some info.  But if the app is not expecting to use the connection for a while, it is better for the app to release the connection back to the pool.

If it is not your scenario, can you explain in detail what you are doing so I don't have to guess and waste everyone's time?

**Comment by glipka** [comment] 2017-07-07 14:18
We are tracing  the application code in order to get more informations about the problem.


Our scenario is : 
-    The app has done a getConnection(). (with a pool)
-     The network drops out somehow.
-     The app uses the connection and gets ORA-3113. 
-     we release the invalid connection
-     we return the error to the app.
-     The app does another getConnection()
-     The app is able to use the connection.


is it possible to trace nodejs Oracle driver execution ?  we don't find how to trace  in the documentation of the driver.
I tried with sqlnet.ora but no trace file is generated. 
Here is the content of my sqlnet.ora file located in /etc

> trace_level_client=admin
> TNSPING.TRACE_LEVEL = admin
> TNSPING.TRACE_DIRECTORY = /tmp/oralog
> trace_file_client = cli.trc
> trace_directory_client = /tmp/oralog
> log_file_client = sqlnet.log
> log_directory_client = /tmp/oralog
> DIAG_ADR_ENABLED=OFF
> 
Best regards
thanks for you help

**Comment by dmcghan** [comment] 2017-07-07 14:35
@glipka Have a look at [this post on enabling trace](https://oracle-base.com/articles/misc/sql-trace-10046-trcsess-and-tkprof). You should be able to do any of those options via the connection when you obtain a connection.

**Comment by cjbj** [comment] 2017-07-08 01:43
So the issue is something is killing the network connection?  Looks like you are on the right track for solving it.  When does the drop out occur?  Is the app idle?

I recall one or two very old cases where a particular invalid SQL statement caused a network drop, but I haven't seen this for a long time.

Firewall timeouts seem to be the most common cause of 'unexplained' network drop outs.

The DBA may find the Oracle server-side trace files show some information about the net disconnection.  And check OS or firewall log files too.

Check your `sqlnet.ora` parameters - try re-enabling `DIAG_ADR_ENABLED`.

At the simplest, have something like this in `sqlnet.ora`

```
ADR_BASE=/tmp/mylogs
TRACE_LEVEL_CLIENT=16
```

Set `TNS_ADMIN` so that Node can read `$TNS_ADMIN/sqlnet.ora` and run `mkdir /tmp/mylogs`.  Execute the app and maybe the traces will show something recognizable.


For everyone's reference, the Oracle Net ADR tracing doc is https://docs.oracle.com/database/122/NETRF/parameters-for-the-sqlnet-ora-file.htm#NETRF398

**Comment by glipka** [comment] 2017-07-12 12:35
Hi  
we have traced the connection (at the client side) 

After adding the option "enable = broken" , in case of error, the  driver reconnect to the database and all is OK.
You can close this point. 

Here is the content of the trace 👍 1124419328) [12-JUL-2017 08:44:20:897] ntt2err: soc 19 error - operation=6, ntresnt[0]=517, ntresnt[1]=32, ntresnt[2]=0
(1124419328) [12-JUL-2017 08:44:20:897] ntt2err: exit
(1124419328) [12-JUL-2017 08:44:20:897] nttfpwr: exit
(1124419328) [12-JUL-2017 08:44:20:897] nserror: entry
(1124419328) [12-JUL-2017 08:44:20:897] nserror: nsres: id=0, op=67, ns=12547, ns2=12560; nt[0]=517, nt[1]=32, nt[2]=0; ora[0]=0, ora[1]=0, ora[2]=0
(1124419328) [12-JUL-2017 08:44:20:897] nsbasic_bsd: exit (-1)
(1124419328) [12-JUL-2017 08:44:20:897] nioqrc: send failed: bl = 1, nicbl = 1
(1124419328) [12-JUL-2017 08:44:20:897] nioqper:  error from nioqrc
(1124419328) [12-JUL-2017 08:44:20:897] nioqper:    ns main err code: 12547
(1124419328) [12-JUL-2017 08:44:20:897] nioqper:    ns (2)  err code: 12560
(1124419328) [12-JUL-2017 08:44:20:897] nioqper:    nt main err code: 517
(1124419328) [12-JUL-2017 08:44:20:897] nioqper:    nt (2)  err code: 32
(1124419328) [12-JUL-2017 08:44:20:897] nioqper:    nt OS   err code: 0
(1124419328) [12-JUL-2017 08:44:20:897] nioqer: entry
(1124419328) [12-JUL-2017 08:44:20:897] nioqer:  incoming err = 12150
(1124419328) [12-JUL-2017 08:44:20:897] nioqce: entry
nscall: connecting...
(1124419328) [12-JUL-2017 08:44:20:905] nlad_expand_hst: Adding an ADDRESS_LIST binding
(1124419328) [12-JUL-2017 08:44:20:905] nlad_expand_hst: Expanding 128.239.24xx
(1124419328) [12-JUL-2017 08:44:20:905] snlinGetAddrInfo: entry
(1124419328) [12-JUL-2017 08:44:20:905] snlinGetAddrInfo: exit
(1124419328) [12-JUL-2017 08:44:20:905] nlad_expand_hst: Already an IP address
(1124419328) [12-JUL-2017 08:44:20:905] snlinFreeAddrInfo: entry
(1124419328) [12-JUL-2017 08:44:20:905] snlinFreeAddrInfo: exit
(1124419328) [12-JUL-2017 08:44:20:905] nlad_expand_hst: Result: (DESCRIPTION=(enable=broken)(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=FUEL)(CID=(PROGRAM=www)(HOST=LNXFRH099700416.enterprise.horsprod.lan)(USER=fioul)))(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=128.aaa.yyy..xxx)(PORT=1521))))
(1124419328) [12-JUL-2017 08:44:20:905] nlad_pr: entry
(1124419328) [12-JUL-2017 08:44:20:905] nlad_pr: description processing
(1124419328) [12-JUL-2017 08:44:20:905] nlad_pr: entry
(1124419328) [12-JUL-2017 08:44:20:905] nlad_pr: Result: (enable=broken)
(1124419328) [12-JUL-2017 08:44:20:905] nlad_pr: entry
(1124419328) [12-JUL-2017 08:44:20:905] nlad_pr: Result: (CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=FUEL)(CID=(PROGRAM=www)(HOST=LNXFRH0997xxxx.enterprise.horsprod.lan)(USER=fioul)))
(1124419328) [12-JUL-2017 08:44:20:905] nlad_pr: ent



Thanks for your help
Best Regards

**Comment by cjbj** [comment] 2017-07-13 01:54
Thanks for the update.

**Closed by cjbj** 2017-07-13 01:54 UTC
Labels: question
