### ISSUE TITLE
Throwing missing expression error when selecting from a query alias

### ISSUE THREAD

**Issue by ziyiwang** [oracle/node-oracledb#568] opened 2016-12-13 02:55 UTC
The file was saved!
ORA-00936: missing expression

received above error when selecting from another query with an alias

select from a select like below, this executes correctly in sql developer but not in node oracledb

        select
          PMOF2.PBR_NUMBER
        from
          (
            select
              PMOF.PMORD_NUMBER,
              PMOF.PBR_NUMBER,
              PMOF.PMORDFIN_YEAR,
              PMOF.PMORDFIN_CAPEX_FLAG,
              PMOF.PMORDFIN_MONTH1,
              PMOF.PMORDFIN_MONTH2,
              PMOF.PMORDFIN_MONTH3,
              PMOF.PMORDFIN_MONTH4,
              PMOF.PMORDFIN_MONTH5,
              PMOF.PMORDFIN_MONTH6,
              PMOF.PMORDFIN_MONTH7,
              PMOF.PMORDFIN_MONTH8,
              PMOF.PMORDFIN_MONTH9,
              PMOF.PMORDFIN_MONTH10,
              PMOF.PMORDFIN_MONTH11,
              PMOF.PMORDFIN_MONTH12
            from
              PMORDFIN_NDSD PMOF
          ) PMOF2
        group by 
          PMOF2.PBR_NUMBER;

**Comment by cjbj** [comment] 2016-12-13 06:02
Works for me.   I checked with Oracle 11.2 & 12.2.

```
sql = 
"select " +
"PMOF2.department_id " +
"from " +
"( " +
"select " +
"PMOF.department_id, " +
"PMOF.last_name " +
"from " +
"employees PMOF " +
") PMOF2 " +
"group by " +
"PMOF2.department_id";
```
gives:
```
[ { DEPARTMENT_ID: 100 },
  { DEPARTMENT_ID: 30 },
  { DEPARTMENT_ID: null },
  { DEPARTMENT_ID: 90 },
  { DEPARTMENT_ID: 20 },
  { DEPARTMENT_ID: 70 },
  { DEPARTMENT_ID: 110 },
  { DEPARTMENT_ID: 50 },
  { DEPARTMENT_ID: 80 },
  { DEPARTMENT_ID: 40 },
  { DEPARTMENT_ID: 60 },
  { DEPARTMENT_ID: 10 } ]
```

The only time I saw `ORA-00936: missing expression` was when I had a dangling comma at the end of the inner column list. 

```sql
CJ@localhost/orcl> select
  2  PMOF2.department_id
  3  from
  4  (
  5    select
  6    PMOF.department_id,
  7    PMOF.last_name,
  8    from
  9    employees PMOF
 10  ) PMOF2
 11  group by
 12  PMOF2.department_id;
  from
  *
ERROR at line 8:
ORA-00936: missing expression
```

If you are still stuck, the best place to ask SQL questions is at Oracle's [Ask Tom](https://asktom.oracle.com)

**Comment by cjbj** [comment] 2017-01-10 04:52
Closing - no update.

**Closed by cjbj** 2017-01-10 04:52 UTC
Labels: question

**Comment by RizziWilliam** [comment] 2019-08-30 15:53
I was having the same issue. My problem was that my first select doesn't return anything, then the `ORA-00936` error shows up.

**Comment by dmcghan** [comment] 2019-08-30 15:55
@RizziWilliam This issue is closed. Please open a new issue and include more details about what you're doing. A reproducible test case is always appreciated (and sometimes required).
