### ISSUE TITLE
Error: ORA-01461: can bind a LONG value only for insert into a LONG column

### ISSUE THREAD

**Issue by jashanbaatth** [oracle/node-oracledb#1577] opened 2023-06-22 04:39 UTC
Creating table using this query -> 
CREATE TABLE sample (id NUMBER, firstfield VARCHAR2(3 char),secondfield VARCHAR(4000 char))

And inserting data using query -> 

 result = await connection1.execute(
      `INSERT INTO "SAMPLE"("FIRSTFIELD","SECONDFIELD") VALUES(:1,:2) RETURNING "ID" into :3`,
      ['李振藩','李小龍李小龍',{type: oracledb.STRING, dir: oracledb.BIND_OUT}],  // Bind values
      { autoCommit: true, outFormat: oracledb.OBJECT }  // Override the default, non-autocommit behavior
    );

It works fine in oracledb@5.5.0 but getting error in oracledb@6.0.0 :- 
Error: ORA-01461: can bind a LONG value only for insert into a LONG column

What bind value or changes I have to do, to make it work?

oracledb 6.0.0
[app.txt](https://github.com/oracle/node-oracledb/files/11828773/app.txt)

**Comment by cjbj** [comment] 2023-06-22 04:51
Start by upgrading to 6.0.1.

**Comment by sharadraju** [comment] 2023-06-22 05:11
@jashanbaatth Thanks for testing node-oracledb.
In your attached file, `app.txt`, there is a minor error. You need to initialize connection2 as
`connection2 = await oracledb.getConnection(dbConfig);`

I have tested this in 6.0.1 and there is no error with the Thick mode. This might be a duplicate of #1554 which was fixed in 6.0.1.

So please upgrade to 6.0.1 and test again.

**Closed** 2023-06-26 15:48 UTC
Labels: duplicate
