### ISSUE TITLE
CLOB segmentation fault (similar to #609?)

### ISSUE THREAD

**Issue by metafloor** [oracle/node-oracledb#623] opened 2017-02-16 20:20 UTC
I get a random seg-fault when selecting on a table with a CLOB column.  If I change the column to VARCHAR, then all is ok.  This may be the same issue as #609 but I am using the low-level callbacks rather than promises.

Below is a self-contained test case of the problem.   It creates the table, inserts 1000 rows, then runs a query-loop over the entire table.  If you set `collen` (column length) to less than 2000, it will create the table using VARCHAR2 and the test will run with no issues.  If you set `collen` to say 15K (to keep under any CLOB-to-string limitation), the query loop will randomly seg-fault.  

Using `oracledb.fetchAsString = [ oracledb.CLOB ]` so that may be part of the issue.

Here is the output from a typical run using a CLOB column:

```
$ node ora-clob.js
node version: v7.5.0
node platform: win32
node arch: x64
oracledb client: 1102000100
oracledb server: 1102000100
drop
create
insert
commit
select
1: 465347373: len=4481
2: 747965830: len=5833
3: 916672497: len=5295
4: 264097537: len=12313
5: 567570119: len=12934
6: 789596721: len=12661
7: 745450679: len=14389
8: 650780345: len=10236
9: 312117845: len=11670
10: 864301361: len=6409
11: 874064911: len=12957
Segmentation fault
```

Using the latest oracledb from npm.

I keep getting an error trying to attach the zip file of the test case so putting it inline instead....

```
var oracledb = require('oracledb');
var dbconfig = require('./dbconfig');

oracledb.fetchAsString = [ oracledb.CLOB ];

// Waterfall steps
var steps = [
   drop,
   create,
   insert,
   commit,
   select,
   drop,
   release
];

//var collen = 1936;      // Use a VARCHAR
var collen = 15*1024;   // Use a CLOB
var connection;

oracledb.getConnection({
      user          : dbconfig.user,
      password      : dbconfig.password,
      connectString : dbconfig.connectString
   },
   function(err, conn) {
      if (err) {
         return console.error(err.message);
      }
      console.log('node version: ' + process.version);
      console.log('node platform: ' + process.platform);
      console.log('node arch: ' + process.arch);
      console.log('oracledb client: ' + oracledb.oracleClientVersion);
      console.log('oracledb server: ' + conn.oracleServerVersion);
      connection = conn;
      next();
   });

// Waterfall
function next() {
   if (steps.length) {
      steps.shift()();
   }
}

function drop() {
   console.log('drop');
   connection.execute("DROP TABLE CLOB_TEST", function(e) {
      // Ignore error
      //if (e) {
      //   console.log(e.stack || e);
      //}
      next();
   });
}

function create() {
   console.log('create');
   connection.execute(`
         CREATE TABLE CLOB_TEST (
            id  INTEGER,
            val ${collen < 2000 ? 'VARCHAR2(' + collen + ')' : 'CLOB'}
         )`, function (e) {
            if (e) {
               return console.log('create: ' + (e.stack || e));
            }
            next();
         });
}

function insert(count) {
   if (!count) {
      count = 0;
      console.log('insert');
   }
   if (count++ > 1000) {
      return next();
   }

   var id = (Math.random() * 1000000000)|0;
   var clob = '';
   var len = (Math.random() * collen * .75 + collen * .25 - 1)|0;
   for (var i = 0; i < len; i++) {
      clob += String.fromCharCode((Math.random() * 96 + 32)|0);
   }
   connection.execute("INSERT INTO CLOB_TEST VALUES (:id, :clob)",
      [ id, clob ],
      function(e) {
         if (e) {
            return console.log('insert: ' + (e.stack || e));
         }
         insert(count);
      });
}

function commit() {
   console.log('commit');
   connection.commit(function(e) {
         if (e) {
            return console.log('commit: ' + (e.stack || e));
         }
         next();
      });
}

function select() {
   console.log('select');
   connection.execute("SELECT * FROM CLOB_TEST", 
         [],
         { resultSet:true },
         function (e,r) {
            if (e) {
               return console.log('select: ' + (e.stack || e));
            }
            r.resultSet.rownbr = 1;
            getrow(r.resultSet);
         });
}

function getrow(resultSet) {
   resultSet.getRow(function(e, r) {
         if (e) {
            return console.log('getrow: ' + (e.stack || e));
         }
         if (r) {
            console.log(resultSet.rownbr + ': ' + r[0] + ': len=' + r[1].length);
            resultSet.rownbr++;
            getrow(resultSet);
         } else {
            console.log('end-of-data');
            resultSet.close(function(e) {
                  if (e) {
                     return console.log('rs-close: ' + (e.stack || e));
                  }
                  next();
               });
         }
      });
}

function release() {
   console.log('release');
   connection.close(
      function(e) {
         if (e) {
            console.error('release: ' + (e.stack || e));
         }
      });
}
```

**Comment by cjbj** [comment] 2017-02-17 00:03
Thanks; reproduces.  We'll take a look.

**Comment by cjbj** [comment] 2017-02-17 16:08
This does have the same root cause as #609 but it was definitely worth opening to check. I'll close this as a dup. I'll be back home next week and we should be able to start release testing for 1.13.

**Closed by cjbj** 2017-02-17 16:08 UTC
Labels: duplicate
