### ISSUE TITLE
Error: DPI-1002: invalid dpiConn 

### ISSUE THREAD

**Issue by giagiac** [oracle/node-oracledb#1160] opened 2019-10-04 14:55 UTC
I had this "warning" than insert fail in a transaction commit... it seams related to something to async... i used callback and library asyc. I don't understand if node-oracledb change async logics.

node 12.11.1
npm 6.11.3
node-oracledb 4.0.1

UnhandledPromiseRejectionWarning: Error: DPI-1002: invalid dpiConn handle
warning.js:27
(node:9496) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

THANKS

**Comment by dmcghan** [comment] 2019-10-04 15:02
Could you please show us the code?

**Comment by giagiac** [comment] 2019-10-04 15:43
Do you notice somethig wrong here? error happens random and it doesn't related to no-one lines of my code... But next to the function doInsertRichiestaPdf (inside there is a BLOB data - it's an interesting information)

app.post('/data/richiesta_pdf', userController.ensureAuthenticated, function (req, res) {

  let richiesta = req.body.data
  let utenteData = req.session.utenteData

  appReq3Hypserv.doInsertRichiestaPdf(utenteData, conf.PARAMS, richiesta, (err) => {
    res.setHeader('Cache-Control', 'no-cache')
    if (err == null) {
      res.json({ result: 'inserimento corretto' })
    }
    else {
      res.json({ result: 'errore', err })
      console.log("E", 'Errore inerimento ricevuta : ' + err);
    }
  })
})

-------------- my go to this ASYNC function ------------------

module.exports.doInsertRichiestaPdf = function (utenteData, PARAMS, richiesta, cb) {

  let AZIENDA_ID = utenteData.AZIENDA_ID
  let COD_CF = utenteData.COD_CF
  let UTENTE_FROM = utenteData.COD_CF

  oracledb.getConnection(
    {
      user: PARAMS.user,
      password: PARAMS.pass,
      connectString: PARAMS.connectString
    },
    (err, conn) => {

      if (err) {
        console.log(err)
        utils.doRelease(conn)
        return;
      }

      async.waterfall([
        function zeroStep(done) {
          doEliminaRichiestePrecedenti(conn, PARAMS, richiesta, done)
        },
        function zeroStep(done) {
          doSelectMAX_PROGR(conn, UTENTE_FROM, AZIENDA_ID, done)
        },
        function firstStep(PROGR, done) {
          //INSERT APP_REQ3_HYPSERV
          buildRichiestaStampa(conn, PARAMS, richiesta, AZIENDA_ID, PROGR, COD_CF, done)
        },
        function secondStep(done) {
          //INSERT APP_REQ3_HYPSERV_APPOGGIO
          buildRichiestaStampaBackup(conn, PARAMS, richiesta, done)
        },
      ],
        function (err) {
          if (err) {
            conn.rollback()
            utils.doRelease(conn)
            cb(err)
          } else {
            conn.commit(function (err) {
              if (err) {
                console.log(err);
                conn.rollback()
              }
              utils.doRelease(conn)
              console.log('Commit della richiesta pdf!')
              cb()
            })
          }
        })
    })
}

**Comment by giagiac** [comment] 2019-10-04 16:05
Full error from journal... i don't well hunderstand where i have to put try catch (in my code that i share after i already use try inside each async.waterfall functions... but nothing change! and it happens randomly

(node:883) UnhandledPromiseRejectionWarning: Error: DPI-1002: invalid dpiConn handle
(node:883) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

**Comment by dmcghan** [comment] 2019-10-04 16:14
@giagiac You're using callbacks and the `async` module. This was great a few years ago, but since then most Node.js devs moved to Promises and then AsyncFunctions (async/await). Read through this series on async patters to get up to speed:
https://jsao.io/2017/06/how-to-get-use-and-close-a-db-connection-using-various-async-patterns/

Switching to async/await will improve your quality of life :)

The biggest issue I see with the current code is the use of `doRelease` (assuming that it calls `close` within), `commit`, and `rollback`. All of these are async operations, but you're not passing callbacks to handle subsequent logic. You may be making similar mistakes in the code you're not showing us.

Keep in mind that our APIs return promises if callbacks are not passed in (so we can support both callbacks and Promises). You're likely not passing in a callback where you meant to, a promise is generated and eventually rejected, and the rejection went unhandled because you didn't anticipate the promise.

The more code you show us the more we can help.

**Comment by giagiac** [comment] 2019-10-04 16:39
Ohh that's great to listen... This is an "old" project that i maintain. I will study to change it!

Which one is better : Promeses or async/await? My goal is to close connection without use a pool cause sometimes connections to db lost (unplug and reboots) and i notice the best solution is make connection every single call. Is this a good solution? Something change now...?

as you requested i show you the rest of the code... i just log the release!

module.exports.doRelease = function (connection) {
  if (connection) {
    connection.release(
      function (err) {
        if (err) {
          console.log(err);
        } else {
          console.log("Connection released!");
        }
      });
  }
}

Thanks @dmcghan

**Comment by dmcghan** [comment] 2019-10-04 16:56
@giagiac async/await builds on top of promises, so you can't have one without the other. Learn a bit about promises and then start using async/await. Only use manual promises when needed for extra control.

> as you requested i show you the rest of the code... i just log the release!

Actually, I'd like to see a lot more of the code, such as `doEliminaRichiestePrecedenti`, `doSelectMAX_PROGR`, `buildRichiestaStampa`, and `buildRichiestaStampaBackup`. This is likely where the issue is.

As for `doRelease`, this function is doing async work. Generally, any function doing async work should provide an async API. If you're using callbacks, then the function should accept a callback that is invoked when the async work is done. If you're using promises, then the function should return a Promise that is resolved when the async work is done.

**Comment by cjbj** [comment] 2019-10-05 01:09
> i notice the best solution is make connection every single call. Is this a good solution? 

No.  It is a slow, inefficient solution.  Using a pool and releasing back to the pool after every call is a better solution.  And even better is to release back to the pool after every related set of operations or after every transaction.  

After you look at Dan's blog series, look at the https://github.com/oracle/node-oracledb/tree/master/examples

**Comment by giagiac** [comment] 2019-10-05 12:18
Thanks a lot! I didn't expect your precious advices!!

I will use the node-oracledb for my new projects with promises in the way as you told me... 

for @dmcghan [i will work to fix al callbacks with promises] as you requested i send one function just to show your the last pieces of the async waterfall (it was very intresting to use the waterfall in the past because i could build an array of "queries" (add more programmatically) and then execute it at runtime - if i well understand i can't do that with promises or i have to study something new)

function buildRichiestaStampaBackup(conn, PARAMS, richiesta, done) {

  var UUID = richiesta.uuid

  // se TIPO_RICEVUTA == null o 0 non c'è niente da fare per nessuno - no incasso no foto da acquisire
  // var TIPO_RICEVUTA = 

  conn.execute(
    `INSERT INTO ` + PARAMS.TABLE_NAME_APP_REQ3_APPOGGIO + ` (CHIAVE_ESTERNA,DATA,DATAORA_RICHIESTA) VALUES (:UUID, :DATA, systimestamp)`,
    {
      UUID,
      DATA: JSON.stringify(richiesta, null, 1)
    }, { autoCommit: false },
    function (err, result) {

      if (err) {
        done(err);
      } else {
        done(null);
      }
    });
}

**Comment by giagiac** [comment] 2019-10-05 12:53
Ops! reading promises tutorial i find out a solution (maybe) at my needs...

return Promise.all(promiseList)

Promises are really new for me.

**Comment by dmcghan** [comment] 2019-10-05 14:49
> for @dmcghan [i will work to fix al callbacks with promises]

Actually, I would advise you to use async/await and only use promises when needed. Have a look at this series on creating a REST API:
https://jsao.io/2018/03/creating-a-rest-api-with-node-js-and-oracle-database/

Note that **services/web-server.js** uses explicit promises because Express APIs don't support promises. In such cases, a function that returns an explicit promise can be used to wrap a callback API.

However, **db_apis/employees.js** doesn't need any promises. The driver supports promises out of the box, so I can just use async/await. Note that async functions return promises implicitly and resolve or reject them based on whether the function returns a value, completes normally or throws an exception.

> return Promise.all(promiseList)

Don't use this API for database work. It sounds good in theory, but in reality, a connection can only do one thing at a time. You will not get any parallelism from using Promise.all with the driver, but you could get buggy code.

**Comment by giagiac** [comment] 2019-10-07 16:21
Yesterday i studied all that you suggest me in Promise.all and i noticed too (i will stay away). Async await very easy, no fear to use it!

Assure you that I will adhere strictly to the rules! Thanks a lot!

**Comment by cjbj** [comment] 2019-10-23 09:50
Closing - I assume this is resolved.

**Closed by cjbj** 2019-10-23 09:50 UTC
Labels: question

**Comment by giagiac** [comment] 2019-11-04 19:26
Thanks a lot - switched my prj to your suggestions (links above) and works like a charm!
