### ISSUE TITLE
OCI-21500 internal error code

### ISSUE THREAD

**Issue by ggrimbert** [oracle/node-oracledb#893] opened 2018-04-17 15:32 UTC
Hi,

I launch many unit tests (about 1380), and sometimes I got the following error : 
```
OCI-21500: internal error code, arguments: [kpuStmtCacheUpdateMemoryStats-remove], [2], [0], [], [], [], [], []


----- Call Stack Trace -----
calling              call     entry                argument values in hex      
location             type     point                (? means dubious value)     
-------------------- -------- -------------------- ----------------------------
skgudmp()+188        call     kgdsdst()            000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
kgerinv_internal()+  call     skgudmp()            000000000 ? 000000000 ?
115                                                000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
kgerinv()+40         call     kgerinv_internal()   000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
kgeasnmierr()+150    call     kgerinv()            000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
kpuStmtCacheUpdateM  call     kgeasnmierr()        000000000 ? 000000000 ?
emoryStats()+379                                   000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
kpuStmtCacheRlsStm(  call     kpuStmtCacheUpdateM  000000000 ? 000000000 ?
)+342                         emoryStats()         000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
kpustmtrelease()+80  call     kpuStmtCacheRlsStm(  000000000 ? 000000000 ?
2                             )                    000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
OCIStmtRelease()+11  call     kpustmtrelease()     000000000 ? 000000000 ?
6                                                  000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
dpiOci__stmtRelease  call     OCIStmtRelease()     000000000 ? 000000000 ?
()+80                                              000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
dpiStmt__close()+44  call     dpiOci__stmtRelease  000000000 ? 000000000 ?
4                             ()                   000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
dpiStmt__free()+27   call     dpiStmt__close()     000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
dpiGen__release()+5  call     dpiStmt__free()      000000000 ? 000000000 ?
1                                                  000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
_ZN12njsResultSet13  call     dpiGen__release()    000000000 ? 000000000 ?
Async_GetRowsEP8njs                                000000000 ? 000000000 ?
Baton()+73                                         000000000 ? 000000000 ?
uv_inet_pton()+993   call     _ZN12njsResultSet13  000000000 ? 000000000 ?
                              Async_GetRowsEP8njs  000000000 ? 000000000 ?
                              Baton()              000000000 ? 000000000 ?
start_thread()+202   call     uv_inet_pton()       000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?

Call stack signature: 0xb63298d7e06a6aea



call stack performance statistics:
total                  : 0.010000 sec
setup                  : 0.010000 sec
stack unwind           : 0.000000 sec
symbol translation     : 0.000000 sec
printing the call stack: 0.000000 sec
printing frame data    : 0.000000 sec
printing argument data : 0.000000 sec


----- End of Call Stack Trace -----

Errors in file :
OCI-21500: internal error code, arguments: [kgepop: no error frame to pop to], [], [], [], [], [], [], []
OCI-21500: internal error code, arguments: [kpuStmtCacheUpdateMemoryStats-remove], [2], [0], [], [], [], [], []


----- Call Stack Trace -----
calling              call     entry                argument values in hex      
location             type     point                (? means dubious value)     
-------------------- -------- -------------------- ----------------------------
skgudmp()+188        call     kgdsdst()            000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
kgerinv_internal()+  call     skgudmp()            000000000 ? 000000000 ?
115                                                000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
kgerinv()+40         call     kgerinv_internal()   000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
kgerin()+130         call     kgerinv()            000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
kgepop()+686         call     kgerin()             000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
kgeasnmierr()+170    call     kgepop()             000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
kpuStmtCacheUpdateM  call     kgeasnmierr()        000000000 ? 000000000 ?
emoryStats()+379                                   000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
kpuStmtCacheRlsStm(  call     kpuStmtCacheUpdateM  000000000 ? 000000000 ?
)+342                         emoryStats()         000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
kpustmtrelease()+80  call     kpuStmtCacheRlsStm(  000000000 ? 000000000 ?
2                             )                    000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
OCIStmtRelease()+11  call     kpustmtrelease()     000000000 ? 000000000 ?
6                                                  000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
dpiOci__stmtRelease  call     OCIStmtRelease()     000000000 ? 000000000 ?
()+80                                              000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
dpiStmt__close()+44  call     dpiOci__stmtRelease  000000000 ? 000000000 ?
4                             ()                   000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
dpiStmt__free()+27   call     dpiStmt__close()     000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
dpiGen__release()+5  call     dpiStmt__free()      000000000 ? 000000000 ?
1                                                  000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
_ZN12njsResultSet13  call     dpiGen__release()    000000000 ? 000000000 ?
Async_GetRowsEP8njs                                000000000 ? 000000000 ?
Baton()+73                                         000000000 ? 000000000 ?
uv_inet_pton()+993   call     _ZN12njsResultSet13  000000000 ? 000000000 ?
                              Async_GetRowsEP8njs  000000000 ? 000000000 ?
                              Baton()              000000000 ? 000000000 ?
start_thread()+202   call     uv_inet_pton()       000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?

Call stack signature: 0x4a67b741c5f0a00e



call stack performance statistics:
total                  : 0.010000 sec
setup                  : 0.000000 sec
stack unwind           : 0.000000 sec
symbol translation     : 0.000000 sec
printing the call stack: 0.010000 sec
printing frame data    : 0.000000 sec
printing argument data : 0.000000 sec


----- End of Call Stack Trace -----

Errors in file :
OCI-21500: internal error code, arguments: [kgepop: no error frame to pop to], [], [], [], [], [], [], []
OCI-21500: internal error code, arguments: [kpuStmtCacheUpdateMemoryStats-remove], [2], [0], [], [], [], [], []


----- Call Stack Trace -----
calling              call     entry                argument values in hex      
location             type     point                (? means dubious value)     
-------------------- -------- -------------------- ----------------------------
skgudmp()+188        call     kgdsdst()            000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
kgepop()+766         call     skgudmp()            000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
kgeasnmierr()+170    call     kgepop()             000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
kpuStmtCacheUpdateM  call     kgeasnmierr()        000000000 ? 000000000 ?
emoryStats()+379                                   000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
kpuStmtCacheRlsStm(  call     kpuStmtCacheUpdateM  000000000 ? 000000000 ?
)+342                         emoryStats()         000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
kpustmtrelease()+80  call     kpuStmtCacheRlsStm(  000000000 ? 000000000 ?
2                             )                    000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
OCIStmtRelease()+11  call     kpustmtrelease()     000000000 ? 000000000 ?
6                                                  000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
dpiOci__stmtRelease  call     OCIStmtRelease()     000000000 ? 000000000 ?
()+80                                              000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
dpiStmt__close()+44  call     dpiOci__stmtRelease  000000000 ? 000000000 ?
4                             ()                   000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
dpiStmt__free()+27   call     dpiStmt__close()     000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
dpiGen__release()+5  call     dpiStmt__free()      000000000 ? 000000000 ?
1                                                  000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
_ZN12njsResultSet13  call     dpiGen__release()    000000000 ? 000000000 ?
Async_GetRowsEP8njs                                000000000 ? 000000000 ?
Baton()+73                                         000000000 ? 000000000 ?
uv_inet_pton()+993   call     _ZN12njsResultSet13  000000000 ? 000000000 ?
                              Async_GetRowsEP8njs  000000000 ? 000000000 ?
                              Baton()              000000000 ? 000000000 ?
start_thread()+202   call     uv_inet_pton()       000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?
                                                   000000000 ? 000000000 ?

Call stack signature: 0xfd580ac9b51af481



call stack performance statistics:
total                  : 0.000000 sec
setup                  : 0.000000 sec
stack unwind           : 0.000000 sec
symbol translation     : 0.000000 sec
printing the call stack: 0.000000 sec
printing frame data    : 0.000000 sec
printing argument data : 0.000000 sec


----- End of Call Stack Trace -----
```

This never happens at the same time or on the same test; the error and stack is always the same. It seems to happen while executing this request : 
```sql
SELECT usrrgtincde, usrincde, profilrgtpnt, dosfolderincde, rgtincde, usrrgtaddpnt, usrrgtduppnt, usrrgtmdfpnt, usrrgtcnspnt, usrrgtprnpnt, usrrgtdltpnt, usrrgtclrpnt, rgtonlinerptpnt, pubfltrdefpnt, usrrgtdefprivcde, operctcincde, rcdcreatehrd, rcdmdfhrd FROM p_usrrgt usrrgt WHERE ((usrrgt.usrincde = 352 AND usrrgt.rgtincde IN (200000551)))
```
This request is executed many times and it doesn't fail at each execution.
My database is on another server, running on Docker. There still plenty of RAM and CPU.

For what I see in the stacktrace, it seems that there's a problem with the stmtcache; but it's set to 0.

I'm sorry but I can't provide a test case as it seems to be failing anytime when more than 500 tests have been launched.

I have no lock on this table or another; no other user connected. Sometimes it works and sometimes don't...

#### Answer the following questions:

1. What is your Node.js version?  Is it 64-bit or 32-bit?  
V 8.11.1 64bits

2. What is your node-oracledb version?
2.2.0

3. What is your Oracle client (e.g. Instant Client) version?  Is it 64-bit or 32-bit?  How was it installed?  Where is it installed?
InstantClient 12.2 64bits; installed from .tar.gz from Oracle website; installed in /opt/oracle/instantclient

4. What is your Oracle Database version?
12.1

5. What is your OS and version?
Ubuntu 16.04 LTS

6. What is your compiler version?  For example, with GCC, run `gcc --version`
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609

7. What Oracle environment variables did you set?  How *exactly* did you set them?
none

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?
echo $LD_LIBRARY_PATH
/opt/oracle/instantclient

9. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
It seems to be a simple Select request

10. What error(s) you are seeing?
OCI-21500: internal error code, arguments: [kpuStmtCacheUpdateMemoryStats-remove], [2], [0], [], [], [], [], []

**Comment by cjbj** [comment] 2018-04-18 03:47
To get some basics, what are the types of the query columns?  Are you changing the table definition during the test run? How do you know you've disabled the statement cache?  Are you using DRCP?

**Comment by ggrimbert** [comment] 2018-04-18 06:31
Here's the table : 
```
Nom              NULL ?   Type         
---------------- -------- ------------ 
USRRGTINCDE      NOT NULL NUMBER(10)   
USRINCDE         NOT NULL NUMBER(10)   
PROFILRGTPNT     NOT NULL NUMBER(1)    
DOSFOLDERINCDE   NOT NULL NUMBER(10)   
RGTINCDE         NOT NULL NUMBER(10)   
USRRGTADDPNT     NOT NULL NUMBER(1)    
USRRGTDUPPNT     NOT NULL NUMBER(1)    
USRRGTMDFPNT     NOT NULL NUMBER(1)    
USRRGTCNSPNT     NOT NULL NUMBER(1)    
USRRGTPRNPNT     NOT NULL NUMBER(1)    
USRRGTDLTPNT     NOT NULL NUMBER(1)    
USRRGTCLRPNT     NOT NULL NUMBER(1)    
RGTONLINERPTPNT  NOT NULL NUMBER(1)    
PUBFLTRDEFPNT    NOT NULL NUMBER(1)    
USRRGTDEFPRIVCDE NOT NULL NUMBER(5)    
OPERCTCINCDE     NOT NULL NUMBER(10)   
RCDCREATEHRD              TIMESTAMP(6) 
RCDMDFHRD                 TIMESTAMP(6) 
```
This table exists from years and I never had any problem. The table definition isn't changed, during my tests I only create / delete some records.
I've disabled the statement cache by passing ```stmtCacheSize : 0```. It's in Sequelize for two years; I had some problems with setting the cache to an another size than 0.

I'm not very sure about DRCP, I know Sequelize creates a pool with 5 connections and these connections are kept alive while the application is running.
I've only noticed this problem during tests execution.

I can provide the full log with all the requests, it contains all requests executed and the stack if this can help you

**Comment by cjbj** [comment] 2018-05-14 08:49
For those following along at home, the root cause seems to be a database bug fixed in Oracle DB 18.  The bug number is 26049373, if anyone needs a backport.

We haven't reproduced the problem in development since the node-oracledb v1 days, so can't comment on what possible mitigations or work arounds might help.

**Comment by cjbj** [comment] 2018-06-08 10:01
Closing - this doesn't appear to be a node-oracledb issue.  If anyone else sees this; check with Oracle Support for the patch for 26049373.

**Closed by cjbj** 2018-06-08 10:01 UTC
Labels: bug

**Comment by zhangyanwei** [comment] 2019-06-27 11:07
I've met this error, but I'm not sure whether it's the same reason?

When I'm using the python to query the data from the Oracle database in multiple threads, this error may(sometimes) come out if I reuse the connection or the cursor.

Maybe this information is useful to you.
